// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module my_filter_v1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        f_V_address0,
        f_V_ce0,
        f_V_q0,
        f_V_address1,
        f_V_ce1,
        f_V_q1,
        adjChImg_V_address0,
        adjChImg_V_ce0,
        adjChImg_V_q0,
        adjChImg_V_address1,
        adjChImg_V_ce1,
        adjChImg_V_q1,
        g1_V_address0,
        g1_V_ce0,
        g1_V_q0,
        g1_V_address1,
        g1_V_ce1,
        g1_V_we1,
        g1_V_d1,
        g1_V_q1,
        g2_V_address0,
        g2_V_ce0,
        g2_V_q0,
        g2_V_address1,
        g2_V_ce1,
        g2_V_we1,
        g2_V_d1,
        g2_V_q1,
        g3_V_address0,
        g3_V_ce0,
        g3_V_q0,
        g3_V_address1,
        g3_V_ce1,
        g3_V_we1,
        g3_V_d1,
        g3_V_q1,
        g4_V_address0,
        g4_V_ce0,
        g4_V_q0,
        g4_V_address1,
        g4_V_ce1,
        g4_V_we1,
        g4_V_d1,
        g4_V_q1,
        g5_V_address0,
        g5_V_ce0,
        g5_V_q0,
        g5_V_address1,
        g5_V_ce1,
        g5_V_we1,
        g5_V_d1,
        g5_V_q1,
        g6_V_address0,
        g6_V_ce0,
        g6_V_q0,
        g7_V_address0,
        g7_V_ce0,
        g7_V_q0
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_pp0_stage0 = 17'd64;
parameter    ap_ST_fsm_state9 = 17'd128;
parameter    ap_ST_fsm_state10 = 17'd256;
parameter    ap_ST_fsm_state11 = 17'd512;
parameter    ap_ST_fsm_state12 = 17'd1024;
parameter    ap_ST_fsm_state13 = 17'd2048;
parameter    ap_ST_fsm_state14 = 17'd4096;
parameter    ap_ST_fsm_state15 = 17'd8192;
parameter    ap_ST_fsm_state16 = 17'd16384;
parameter    ap_ST_fsm_state17 = 17'd32768;
parameter    ap_ST_fsm_state18 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] f_V_address0;
output   f_V_ce0;
input  [7:0] f_V_q0;
output  [13:0] f_V_address1;
output   f_V_ce1;
input  [7:0] f_V_q1;
output  [13:0] adjChImg_V_address0;
output   adjChImg_V_ce0;
input  [7:0] adjChImg_V_q0;
output  [13:0] adjChImg_V_address1;
output   adjChImg_V_ce1;
input  [7:0] adjChImg_V_q1;
output  [13:0] g1_V_address0;
output   g1_V_ce0;
input  [7:0] g1_V_q0;
output  [13:0] g1_V_address1;
output   g1_V_ce1;
output   g1_V_we1;
output  [7:0] g1_V_d1;
input  [7:0] g1_V_q1;
output  [13:0] g2_V_address0;
output   g2_V_ce0;
input  [7:0] g2_V_q0;
output  [13:0] g2_V_address1;
output   g2_V_ce1;
output   g2_V_we1;
output  [7:0] g2_V_d1;
input  [7:0] g2_V_q1;
output  [13:0] g3_V_address0;
output   g3_V_ce0;
input  [7:0] g3_V_q0;
output  [13:0] g3_V_address1;
output   g3_V_ce1;
output   g3_V_we1;
output  [7:0] g3_V_d1;
input  [7:0] g3_V_q1;
output  [13:0] g4_V_address0;
output   g4_V_ce0;
input  [7:0] g4_V_q0;
output  [13:0] g4_V_address1;
output   g4_V_ce1;
output   g4_V_we1;
output  [7:0] g4_V_d1;
input  [7:0] g4_V_q1;
output  [13:0] g5_V_address0;
output   g5_V_ce0;
input  [7:0] g5_V_q0;
output  [13:0] g5_V_address1;
output   g5_V_ce1;
output   g5_V_we1;
output  [7:0] g5_V_d1;
input  [7:0] g5_V_q1;
output  [13:0] g6_V_address0;
output   g6_V_ce0;
input  [0:0] g6_V_q0;
output  [13:0] g7_V_address0;
output   g7_V_ce0;
input  [0:0] g7_V_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[13:0] f_V_address0;
reg f_V_ce0;
reg[13:0] f_V_address1;
reg f_V_ce1;
reg[13:0] adjChImg_V_address0;
reg adjChImg_V_ce0;
reg[13:0] adjChImg_V_address1;
reg adjChImg_V_ce1;
reg[13:0] g1_V_address0;
reg g1_V_ce0;
reg[13:0] g1_V_address1;
reg g1_V_ce1;
reg g1_V_we1;
reg[13:0] g2_V_address0;
reg g2_V_ce0;
reg[13:0] g2_V_address1;
reg g2_V_ce1;
reg g2_V_we1;
reg[13:0] g3_V_address0;
reg g3_V_ce0;
reg[13:0] g3_V_address1;
reg g3_V_ce1;
reg g3_V_we1;
reg[13:0] g4_V_address0;
reg g4_V_ce0;
reg[13:0] g4_V_address1;
reg g4_V_ce1;
reg g4_V_we1;
reg[13:0] g5_V_address0;
reg g5_V_ce0;
reg[13:0] g5_V_address1;
reg g5_V_ce1;
reg g5_V_we1;
reg g6_V_ce0;
reg g7_V_ce0;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [14:0] indvar_flatten_reg_307;
reg   [7:0] y76_0_reg_318;
reg   [7:0] x77_0_reg_329;
wire   [0:0] icmp_ln126_fu_402_p2;
reg   [0:0] icmp_ln126_reg_641;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state7_pp0_stage0_iter0;
wire    ap_block_state8_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [14:0] add_ln126_fu_408_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [7:0] select_ln131_1_fu_434_p3;
reg   [7:0] select_ln131_1_reg_650;
reg   [13:0] g1_V_addr_reg_655;
reg   [13:0] g2_V_addr_reg_661;
reg   [13:0] g3_V_addr_reg_667;
reg   [13:0] g4_V_addr_reg_673;
reg   [13:0] g5_V_addr_reg_679;
wire   [7:0] x_1_fu_473_p2;
wire   [7:0] y_1_fu_565_p2;
reg   [7:0] y_1_reg_708;
wire    ap_CS_fsm_state15;
wire   [15:0] zext_ln172_fu_579_p1;
reg   [15:0] zext_ln172_reg_713;
wire   [0:0] icmp_ln170_fu_559_p2;
wire   [7:0] x_fu_589_p2;
reg   [7:0] x_reg_721;
wire    ap_CS_fsm_state16;
wire   [63:0] zext_ln215_3_fu_604_p1;
reg   [63:0] zext_ln215_3_reg_726;
wire   [0:0] icmp_ln172_fu_583_p2;
wire    ap_CS_fsm_state6;
wire    grp_my_filter_fy5_fu_362_ap_ready;
wire    grp_my_filter_fy5_fu_362_ap_done;
wire    grp_my_filter_fy5_fu_369_ap_ready;
wire    grp_my_filter_fy5_fu_369_ap_done;
wire    grp_my_filter_fy5_fu_375_ap_ready;
wire    grp_my_filter_fy5_fu_375_ap_done;
reg    ap_block_state6_on_subcall_done;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state7;
reg    ap_enable_reg_pp0_iter1;
reg   [13:0] fx_V_address0;
reg    fx_V_ce0;
reg    fx_V_we0;
wire   [7:0] fx_V_q0;
reg   [13:0] fx_V_address1;
reg    fx_V_ce1;
wire   [7:0] fx_V_q1;
reg   [13:0] fy_V_address0;
reg    fy_V_ce0;
reg    fy_V_we0;
wire   [7:0] fy_V_q0;
reg    fy_V_ce1;
wire   [7:0] fy_V_q1;
reg    fxx_ce0;
reg    fxx_we0;
reg    fyy_ce0;
reg    fyy_we0;
reg    fxy_ce0;
reg    fxy_we0;
reg    adj_fx_ce0;
reg    adj_fx_we0;
reg    adj_fy_ce0;
reg    adj_fy_we0;
reg    gx_ce0;
reg    gx_we0;
reg    gy_ce0;
reg    gy_we0;
reg   [13:0] g3x_V_address0;
reg    g3x_V_ce0;
reg    g3x_V_we0;
wire   [7:0] g3x_V_q0;
reg    g3x_V_ce1;
wire   [7:0] g3x_V_q1;
reg    gxx_ce0;
reg    gxx_we0;
reg   [13:0] g4y_V_address0;
reg    g4y_V_ce0;
reg    g4y_V_we0;
wire   [7:0] g4y_V_q0;
reg    g4y_V_ce1;
wire   [7:0] g4y_V_q1;
reg    gyy_ce0;
reg    gyy_we0;
reg   [13:0] g5x_V_address0;
reg    g5x_V_ce0;
reg    g5x_V_we0;
wire   [7:0] g5x_V_q0;
reg    g5x_V_ce1;
wire   [7:0] g5x_V_q1;
reg    gxy_ce0;
reg    gxy_we0;
reg   [13:0] temp_cross6_V_address0;
reg    temp_cross6_V_ce0;
reg    temp_cross6_V_we0;
wire   [7:0] temp_cross6_V_d0;
wire   [7:0] temp_cross6_V_q0;
reg    temp_cross6_V_ce1;
wire   [7:0] temp_cross6_V_q1;
reg   [13:0] temp_cross7_V_address0;
reg    temp_cross7_V_ce0;
reg    temp_cross7_V_we0;
wire   [7:0] temp_cross7_V_d0;
wire   [7:0] temp_cross7_V_q0;
reg    temp_cross7_V_ce1;
wire   [7:0] temp_cross7_V_q1;
reg    cross_X_ce0;
reg    cross_X_we0;
reg    cross_Y_ce0;
reg    cross_Y_we0;
wire    grp_my_filter_fy5_fu_362_ap_start;
wire    grp_my_filter_fy5_fu_362_ap_idle;
wire   [13:0] grp_my_filter_fy5_fu_362_data_out_V_address0;
wire    grp_my_filter_fy5_fu_362_data_out_V_ce0;
wire    grp_my_filter_fy5_fu_362_data_out_V_we0;
wire   [7:0] grp_my_filter_fy5_fu_362_data_out_V_d0;
wire   [13:0] grp_my_filter_fy5_fu_362_data_in_V_address0;
wire    grp_my_filter_fy5_fu_362_data_in_V_ce0;
reg   [7:0] grp_my_filter_fy5_fu_362_data_in_V_q0;
wire   [13:0] grp_my_filter_fy5_fu_362_data_in_V_address1;
wire    grp_my_filter_fy5_fu_362_data_in_V_ce1;
reg   [7:0] grp_my_filter_fy5_fu_362_data_in_V_q1;
wire    grp_my_filter_fy5_fu_369_ap_start;
wire    grp_my_filter_fy5_fu_369_ap_idle;
wire   [13:0] grp_my_filter_fy5_fu_369_data_out_V_address0;
wire    grp_my_filter_fy5_fu_369_data_out_V_ce0;
wire    grp_my_filter_fy5_fu_369_data_out_V_we0;
wire   [7:0] grp_my_filter_fy5_fu_369_data_out_V_d0;
wire   [13:0] grp_my_filter_fy5_fu_369_data_in_V_address0;
wire    grp_my_filter_fy5_fu_369_data_in_V_ce0;
reg   [7:0] grp_my_filter_fy5_fu_369_data_in_V_q0;
wire   [13:0] grp_my_filter_fy5_fu_369_data_in_V_address1;
wire    grp_my_filter_fy5_fu_369_data_in_V_ce1;
reg   [7:0] grp_my_filter_fy5_fu_369_data_in_V_q1;
wire    grp_my_filter_fy5_fu_375_ap_start;
wire    grp_my_filter_fy5_fu_375_ap_idle;
wire   [13:0] grp_my_filter_fy5_fu_375_data_out_V_address0;
wire    grp_my_filter_fy5_fu_375_data_out_V_ce0;
wire    grp_my_filter_fy5_fu_375_data_out_V_we0;
wire   [7:0] grp_my_filter_fy5_fu_375_data_out_V_d0;
wire   [13:0] grp_my_filter_fy5_fu_375_data_in_V_address0;
wire    grp_my_filter_fy5_fu_375_data_in_V_ce0;
reg   [7:0] grp_my_filter_fy5_fu_375_data_in_V_q0;
wire   [13:0] grp_my_filter_fy5_fu_375_data_in_V_address1;
wire    grp_my_filter_fy5_fu_375_data_in_V_ce1;
reg   [7:0] grp_my_filter_fy5_fu_375_data_in_V_q1;
wire    grp_my_filter_fx6_fu_384_ap_start;
wire    grp_my_filter_fx6_fu_384_ap_done;
wire    grp_my_filter_fx6_fu_384_ap_idle;
wire    grp_my_filter_fx6_fu_384_ap_ready;
wire   [13:0] grp_my_filter_fx6_fu_384_data_out_V_address0;
wire    grp_my_filter_fx6_fu_384_data_out_V_ce0;
wire    grp_my_filter_fx6_fu_384_data_out_V_we0;
wire   [7:0] grp_my_filter_fx6_fu_384_data_out_V_d0;
wire   [13:0] grp_my_filter_fx6_fu_384_data_in_V_address0;
wire    grp_my_filter_fx6_fu_384_data_in_V_ce0;
reg   [7:0] grp_my_filter_fx6_fu_384_data_in_V_q0;
wire   [13:0] grp_my_filter_fx6_fu_384_data_in_V_address1;
wire    grp_my_filter_fx6_fu_384_data_in_V_ce1;
reg   [7:0] grp_my_filter_fx6_fu_384_data_in_V_q1;
wire    grp_my_filter_fx6_fu_392_ap_start;
wire    grp_my_filter_fx6_fu_392_ap_done;
wire    grp_my_filter_fx6_fu_392_ap_idle;
wire    grp_my_filter_fx6_fu_392_ap_ready;
wire   [13:0] grp_my_filter_fx6_fu_392_data_out_V_address0;
wire    grp_my_filter_fx6_fu_392_data_out_V_ce0;
wire    grp_my_filter_fx6_fu_392_data_out_V_we0;
wire   [7:0] grp_my_filter_fx6_fu_392_data_out_V_d0;
wire   [13:0] grp_my_filter_fx6_fu_392_data_in_V_address0;
wire    grp_my_filter_fx6_fu_392_data_in_V_ce0;
reg   [7:0] grp_my_filter_fx6_fu_392_data_in_V_q0;
wire   [13:0] grp_my_filter_fx6_fu_392_data_in_V_address1;
wire    grp_my_filter_fx6_fu_392_data_in_V_ce1;
reg   [7:0] grp_my_filter_fx6_fu_392_data_in_V_q1;
reg   [7:0] ap_phi_mux_y76_0_phi_fu_322_p4;
wire    ap_block_pp0_stage0;
reg   [7:0] y95_0_reg_340;
wire    ap_CS_fsm_state14;
reg    ap_block_state14_on_subcall_done;
reg   [7:0] x96_0_reg_351;
wire    ap_CS_fsm_state17;
reg    grp_my_filter_fy5_fu_362_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state18;
reg    grp_my_filter_fy5_fu_369_ap_start_reg;
reg    grp_my_filter_fy5_fu_375_ap_start_reg;
reg    grp_my_filter_fx6_fu_384_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state10;
reg    grp_my_filter_fx6_fu_392_ap_start_reg;
wire   [63:0] zext_ln215_1_fu_464_p1;
wire   [0:0] icmp_ln895_fu_489_p2;
wire   [0:0] icmp_ln895_1_fu_505_p2;
wire   [0:0] icmp_ln895_2_fu_521_p2;
wire   [0:0] icmp_ln895_3_fu_537_p2;
wire   [0:0] icmp_ln895_4_fu_553_p2;
wire   [0:0] icmp_ln128_fu_420_p2;
wire   [7:0] y_fu_414_p2;
wire   [14:0] tmp_fu_442_p3;
wire   [7:0] select_ln131_fu_426_p3;
wire   [15:0] zext_ln215_fu_454_p1;
wire   [15:0] zext_ln129_fu_450_p1;
wire   [15:0] add_ln215_fu_458_p2;
wire   [6:0] tmp_2_fu_479_p4;
wire   [6:0] tmp_5_fu_495_p4;
wire   [6:0] tmp_6_fu_511_p4;
wire   [6:0] tmp_7_fu_527_p4;
wire   [6:0] tmp_8_fu_543_p4;
wire   [14:0] tmp_1_fu_571_p3;
wire   [15:0] zext_ln215_2_fu_595_p1;
wire   [15:0] add_ln215_1_fu_599_p2;
wire   [7:0] select_ln209_fu_611_p3;
wire   [7:0] select_ln209_1_fu_626_p3;
reg    ap_block_state18_on_subcall_done;
reg   [16:0] ap_NS_fsm;
reg    ap_block_state4_on_subcall_done;
reg    ap_block_state12_on_subcall_done;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 grp_my_filter_fy5_fu_362_ap_start_reg = 1'b0;
#0 grp_my_filter_fy5_fu_369_ap_start_reg = 1'b0;
#0 grp_my_filter_fy5_fu_375_ap_start_reg = 1'b0;
#0 grp_my_filter_fx6_fu_384_ap_start_reg = 1'b0;
#0 grp_my_filter_fx6_fu_392_ap_start_reg = 1'b0;
end

my_filter_v1_fx_V #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
fx_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fx_V_address0),
    .ce0(fx_V_ce0),
    .we0(fx_V_we0),
    .d0(grp_my_filter_fx6_fu_384_data_out_V_d0),
    .q0(fx_V_q0),
    .address1(fx_V_address1),
    .ce1(fx_V_ce1),
    .q1(fx_V_q1)
);

my_filter_v1_fx_V #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
fy_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fy_V_address0),
    .ce0(fy_V_ce0),
    .we0(fy_V_we0),
    .d0(grp_my_filter_fy5_fu_362_data_out_V_d0),
    .q0(fy_V_q0),
    .address1(grp_my_filter_fy5_fu_362_data_in_V_address1),
    .ce1(fy_V_ce1),
    .q1(fy_V_q1)
);

my_filter_v1_fxx #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
fxx_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_my_filter_fx6_fu_384_data_out_V_address0),
    .ce0(fxx_ce0),
    .we0(fxx_we0),
    .d0(grp_my_filter_fx6_fu_384_data_out_V_d0)
);

my_filter_v1_fxx #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
fyy_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_my_filter_fy5_fu_362_data_out_V_address0),
    .ce0(fyy_ce0),
    .we0(fyy_we0),
    .d0(grp_my_filter_fy5_fu_362_data_out_V_d0)
);

my_filter_v1_fxx #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
fxy_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_my_filter_fy5_fu_369_data_out_V_address0),
    .ce0(fxy_ce0),
    .we0(fxy_we0),
    .d0(grp_my_filter_fy5_fu_369_data_out_V_d0)
);

my_filter_v1_fxx #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
adj_fx_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_my_filter_fx6_fu_392_data_out_V_address0),
    .ce0(adj_fx_ce0),
    .we0(adj_fx_we0),
    .d0(grp_my_filter_fx6_fu_392_data_out_V_d0)
);

my_filter_v1_fxx #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
adj_fy_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_my_filter_fy5_fu_375_data_out_V_address0),
    .ce0(adj_fy_ce0),
    .we0(adj_fy_we0),
    .d0(grp_my_filter_fy5_fu_375_data_out_V_d0)
);

my_filter_v1_fxx #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
gx_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_my_filter_fx6_fu_384_data_out_V_address0),
    .ce0(gx_ce0),
    .we0(gx_we0),
    .d0(grp_my_filter_fx6_fu_384_data_out_V_d0)
);

my_filter_v1_fxx #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
gy_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_my_filter_fy5_fu_362_data_out_V_address0),
    .ce0(gy_ce0),
    .we0(gy_we0),
    .d0(grp_my_filter_fy5_fu_362_data_out_V_d0)
);

my_filter_v1_fx_V #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
g3x_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(g3x_V_address0),
    .ce0(g3x_V_ce0),
    .we0(g3x_V_we0),
    .d0(grp_my_filter_fx6_fu_392_data_out_V_d0),
    .q0(g3x_V_q0),
    .address1(grp_my_filter_fx6_fu_384_data_in_V_address1),
    .ce1(g3x_V_ce1),
    .q1(g3x_V_q1)
);

my_filter_v1_fxx #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
gxx_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_my_filter_fx6_fu_384_data_out_V_address0),
    .ce0(gxx_ce0),
    .we0(gxx_we0),
    .d0(grp_my_filter_fx6_fu_384_data_out_V_d0)
);

my_filter_v1_fx_V #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
g4y_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(g4y_V_address0),
    .ce0(g4y_V_ce0),
    .we0(g4y_V_we0),
    .d0(grp_my_filter_fy5_fu_369_data_out_V_d0),
    .q0(g4y_V_q0),
    .address1(grp_my_filter_fy5_fu_362_data_in_V_address1),
    .ce1(g4y_V_ce1),
    .q1(g4y_V_q1)
);

my_filter_v1_fxx #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
gyy_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_my_filter_fy5_fu_362_data_out_V_address0),
    .ce0(gyy_ce0),
    .we0(gyy_we0),
    .d0(grp_my_filter_fy5_fu_362_data_out_V_d0)
);

my_filter_v1_fx_V #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
g5x_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(g5x_V_address0),
    .ce0(g5x_V_ce0),
    .we0(g5x_V_we0),
    .d0(grp_my_filter_fx6_fu_384_data_out_V_d0),
    .q0(g5x_V_q0),
    .address1(grp_my_filter_fy5_fu_375_data_in_V_address1),
    .ce1(g5x_V_ce1),
    .q1(g5x_V_q1)
);

my_filter_v1_fxx #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
gxy_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_my_filter_fy5_fu_375_data_out_V_address0),
    .ce0(gxy_ce0),
    .we0(gxy_we0),
    .d0(grp_my_filter_fy5_fu_375_data_out_V_d0)
);

my_filter_v1_fx_V #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
temp_cross6_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_cross6_V_address0),
    .ce0(temp_cross6_V_ce0),
    .we0(temp_cross6_V_we0),
    .d0(temp_cross6_V_d0),
    .q0(temp_cross6_V_q0),
    .address1(grp_my_filter_fx6_fu_384_data_in_V_address1),
    .ce1(temp_cross6_V_ce1),
    .q1(temp_cross6_V_q1)
);

my_filter_v1_fx_V #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
temp_cross7_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_cross7_V_address0),
    .ce0(temp_cross7_V_ce0),
    .we0(temp_cross7_V_we0),
    .d0(temp_cross7_V_d0),
    .q0(temp_cross7_V_q0),
    .address1(grp_my_filter_fy5_fu_362_data_in_V_address1),
    .ce1(temp_cross7_V_ce1),
    .q1(temp_cross7_V_q1)
);

my_filter_v1_fxx #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
cross_X_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_my_filter_fx6_fu_384_data_out_V_address0),
    .ce0(cross_X_ce0),
    .we0(cross_X_we0),
    .d0(grp_my_filter_fx6_fu_384_data_out_V_d0)
);

my_filter_v1_fxx #(
    .DataWidth( 8 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
cross_Y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_my_filter_fy5_fu_362_data_out_V_address0),
    .ce0(cross_Y_ce0),
    .we0(cross_Y_we0),
    .d0(grp_my_filter_fy5_fu_362_data_out_V_d0)
);

my_filter_fy5 grp_my_filter_fy5_fu_362(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_my_filter_fy5_fu_362_ap_start),
    .ap_done(grp_my_filter_fy5_fu_362_ap_done),
    .ap_idle(grp_my_filter_fy5_fu_362_ap_idle),
    .ap_ready(grp_my_filter_fy5_fu_362_ap_ready),
    .data_out_V_address0(grp_my_filter_fy5_fu_362_data_out_V_address0),
    .data_out_V_ce0(grp_my_filter_fy5_fu_362_data_out_V_ce0),
    .data_out_V_we0(grp_my_filter_fy5_fu_362_data_out_V_we0),
    .data_out_V_d0(grp_my_filter_fy5_fu_362_data_out_V_d0),
    .data_in_V_address0(grp_my_filter_fy5_fu_362_data_in_V_address0),
    .data_in_V_ce0(grp_my_filter_fy5_fu_362_data_in_V_ce0),
    .data_in_V_q0(grp_my_filter_fy5_fu_362_data_in_V_q0),
    .data_in_V_address1(grp_my_filter_fy5_fu_362_data_in_V_address1),
    .data_in_V_ce1(grp_my_filter_fy5_fu_362_data_in_V_ce1),
    .data_in_V_q1(grp_my_filter_fy5_fu_362_data_in_V_q1)
);

my_filter_fy5 grp_my_filter_fy5_fu_369(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_my_filter_fy5_fu_369_ap_start),
    .ap_done(grp_my_filter_fy5_fu_369_ap_done),
    .ap_idle(grp_my_filter_fy5_fu_369_ap_idle),
    .ap_ready(grp_my_filter_fy5_fu_369_ap_ready),
    .data_out_V_address0(grp_my_filter_fy5_fu_369_data_out_V_address0),
    .data_out_V_ce0(grp_my_filter_fy5_fu_369_data_out_V_ce0),
    .data_out_V_we0(grp_my_filter_fy5_fu_369_data_out_V_we0),
    .data_out_V_d0(grp_my_filter_fy5_fu_369_data_out_V_d0),
    .data_in_V_address0(grp_my_filter_fy5_fu_369_data_in_V_address0),
    .data_in_V_ce0(grp_my_filter_fy5_fu_369_data_in_V_ce0),
    .data_in_V_q0(grp_my_filter_fy5_fu_369_data_in_V_q0),
    .data_in_V_address1(grp_my_filter_fy5_fu_369_data_in_V_address1),
    .data_in_V_ce1(grp_my_filter_fy5_fu_369_data_in_V_ce1),
    .data_in_V_q1(grp_my_filter_fy5_fu_369_data_in_V_q1)
);

my_filter_fy5 grp_my_filter_fy5_fu_375(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_my_filter_fy5_fu_375_ap_start),
    .ap_done(grp_my_filter_fy5_fu_375_ap_done),
    .ap_idle(grp_my_filter_fy5_fu_375_ap_idle),
    .ap_ready(grp_my_filter_fy5_fu_375_ap_ready),
    .data_out_V_address0(grp_my_filter_fy5_fu_375_data_out_V_address0),
    .data_out_V_ce0(grp_my_filter_fy5_fu_375_data_out_V_ce0),
    .data_out_V_we0(grp_my_filter_fy5_fu_375_data_out_V_we0),
    .data_out_V_d0(grp_my_filter_fy5_fu_375_data_out_V_d0),
    .data_in_V_address0(grp_my_filter_fy5_fu_375_data_in_V_address0),
    .data_in_V_ce0(grp_my_filter_fy5_fu_375_data_in_V_ce0),
    .data_in_V_q0(grp_my_filter_fy5_fu_375_data_in_V_q0),
    .data_in_V_address1(grp_my_filter_fy5_fu_375_data_in_V_address1),
    .data_in_V_ce1(grp_my_filter_fy5_fu_375_data_in_V_ce1),
    .data_in_V_q1(grp_my_filter_fy5_fu_375_data_in_V_q1)
);

my_filter_fx6 grp_my_filter_fx6_fu_384(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_my_filter_fx6_fu_384_ap_start),
    .ap_done(grp_my_filter_fx6_fu_384_ap_done),
    .ap_idle(grp_my_filter_fx6_fu_384_ap_idle),
    .ap_ready(grp_my_filter_fx6_fu_384_ap_ready),
    .data_out_V_address0(grp_my_filter_fx6_fu_384_data_out_V_address0),
    .data_out_V_ce0(grp_my_filter_fx6_fu_384_data_out_V_ce0),
    .data_out_V_we0(grp_my_filter_fx6_fu_384_data_out_V_we0),
    .data_out_V_d0(grp_my_filter_fx6_fu_384_data_out_V_d0),
    .data_in_V_address0(grp_my_filter_fx6_fu_384_data_in_V_address0),
    .data_in_V_ce0(grp_my_filter_fx6_fu_384_data_in_V_ce0),
    .data_in_V_q0(grp_my_filter_fx6_fu_384_data_in_V_q0),
    .data_in_V_address1(grp_my_filter_fx6_fu_384_data_in_V_address1),
    .data_in_V_ce1(grp_my_filter_fx6_fu_384_data_in_V_ce1),
    .data_in_V_q1(grp_my_filter_fx6_fu_384_data_in_V_q1)
);

my_filter_fx6 grp_my_filter_fx6_fu_392(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_my_filter_fx6_fu_392_ap_start),
    .ap_done(grp_my_filter_fx6_fu_392_ap_done),
    .ap_idle(grp_my_filter_fx6_fu_392_ap_idle),
    .ap_ready(grp_my_filter_fx6_fu_392_ap_ready),
    .data_out_V_address0(grp_my_filter_fx6_fu_392_data_out_V_address0),
    .data_out_V_ce0(grp_my_filter_fx6_fu_392_data_out_V_ce0),
    .data_out_V_we0(grp_my_filter_fx6_fu_392_data_out_V_we0),
    .data_out_V_d0(grp_my_filter_fx6_fu_392_data_out_V_d0),
    .data_in_V_address0(grp_my_filter_fx6_fu_392_data_in_V_address0),
    .data_in_V_ce0(grp_my_filter_fx6_fu_392_data_in_V_ce0),
    .data_in_V_q0(grp_my_filter_fx6_fu_392_data_in_V_q0),
    .data_in_V_address1(grp_my_filter_fx6_fu_392_data_in_V_address1),
    .data_in_V_ce1(grp_my_filter_fx6_fu_392_data_in_V_ce1),
    .data_in_V_q1(grp_my_filter_fx6_fu_392_data_in_V_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state7) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state7))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state7);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_my_filter_fx6_fu_384_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state15) & (icmp_ln170_fu_559_p2 == 1'd1)))) begin
            grp_my_filter_fx6_fu_384_ap_start_reg <= 1'b1;
        end else if ((grp_my_filter_fx6_fu_384_ap_ready == 1'b1)) begin
            grp_my_filter_fx6_fu_384_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_my_filter_fx6_fu_392_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state3))) begin
            grp_my_filter_fx6_fu_392_ap_start_reg <= 1'b1;
        end else if ((grp_my_filter_fx6_fu_392_ap_ready == 1'b1)) begin
            grp_my_filter_fx6_fu_392_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_my_filter_fy5_fu_362_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state15) & (icmp_ln170_fu_559_p2 == 1'd1)))) begin
            grp_my_filter_fy5_fu_362_ap_start_reg <= 1'b1;
        end else if ((grp_my_filter_fy5_fu_362_ap_ready == 1'b1)) begin
            grp_my_filter_fy5_fu_362_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_my_filter_fy5_fu_369_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
            grp_my_filter_fy5_fu_369_ap_start_reg <= 1'b1;
        end else if ((grp_my_filter_fy5_fu_369_ap_ready == 1'b1)) begin
            grp_my_filter_fy5_fu_369_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_my_filter_fy5_fu_375_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
            grp_my_filter_fy5_fu_375_ap_start_reg <= 1'b1;
        end else if ((grp_my_filter_fy5_fu_375_ap_ready == 1'b1)) begin
            grp_my_filter_fy5_fu_375_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln126_fu_402_p2 == 1'd0))) begin
        indvar_flatten_reg_307 <= add_ln126_fu_408_p2;
    end else if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
        indvar_flatten_reg_307 <= 15'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln126_fu_402_p2 == 1'd0))) begin
        x77_0_reg_329 <= x_1_fu_473_p2;
    end else if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
        x77_0_reg_329 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        x96_0_reg_351 <= x_reg_721;
    end else if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln170_fu_559_p2 == 1'd0))) begin
        x96_0_reg_351 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln126_reg_641 == 1'd0))) begin
        y76_0_reg_318 <= select_ln131_1_reg_650;
    end else if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
        y76_0_reg_318 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state14_on_subcall_done) & (1'b1 == ap_CS_fsm_state14))) begin
        y95_0_reg_340 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state16) & (icmp_ln172_fu_583_p2 == 1'd1))) begin
        y95_0_reg_340 <= y_1_reg_708;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln126_fu_402_p2 == 1'd0))) begin
        g1_V_addr_reg_655 <= zext_ln215_1_fu_464_p1;
        g2_V_addr_reg_661 <= zext_ln215_1_fu_464_p1;
        g3_V_addr_reg_667 <= zext_ln215_1_fu_464_p1;
        g4_V_addr_reg_673 <= zext_ln215_1_fu_464_p1;
        g5_V_addr_reg_679 <= zext_ln215_1_fu_464_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln126_reg_641 <= icmp_ln126_fu_402_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln126_fu_402_p2 == 1'd0))) begin
        select_ln131_1_reg_650 <= select_ln131_1_fu_434_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        x_reg_721 <= x_fu_589_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        y_1_reg_708 <= y_1_fu_565_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln170_fu_559_p2 == 1'd0))) begin
        zext_ln172_reg_713[14 : 7] <= zext_ln172_fu_579_p1[14 : 7];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (icmp_ln172_fu_583_p2 == 1'd0))) begin
        zext_ln215_3_reg_726[15 : 0] <= zext_ln215_3_fu_604_p1[15 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        adjChImg_V_address0 = zext_ln215_3_fu_604_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        adjChImg_V_address0 = grp_my_filter_fx6_fu_392_data_in_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        adjChImg_V_address0 = grp_my_filter_fy5_fu_375_data_in_V_address0;
    end else begin
        adjChImg_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        adjChImg_V_address1 = grp_my_filter_fx6_fu_392_data_in_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        adjChImg_V_address1 = grp_my_filter_fy5_fu_375_data_in_V_address1;
    end else begin
        adjChImg_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        adjChImg_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        adjChImg_V_ce0 = grp_my_filter_fx6_fu_392_data_in_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        adjChImg_V_ce0 = grp_my_filter_fy5_fu_375_data_in_V_ce0;
    end else begin
        adjChImg_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        adjChImg_V_ce1 = grp_my_filter_fx6_fu_392_data_in_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        adjChImg_V_ce1 = grp_my_filter_fy5_fu_375_data_in_V_ce1;
    end else begin
        adjChImg_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        adj_fx_ce0 = grp_my_filter_fx6_fu_392_data_out_V_ce0;
    end else begin
        adj_fx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        adj_fx_we0 = grp_my_filter_fx6_fu_392_data_out_V_we0;
    end else begin
        adj_fx_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        adj_fy_ce0 = grp_my_filter_fy5_fu_375_data_out_V_ce0;
    end else begin
        adj_fy_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        adj_fy_we0 = grp_my_filter_fy5_fu_375_data_out_V_we0;
    end else begin
        adj_fy_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln126_fu_402_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state7 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state7 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln126_reg_641 == 1'd0))) begin
        ap_phi_mux_y76_0_phi_fu_322_p4 = select_ln131_1_reg_650;
    end else begin
        ap_phi_mux_y76_0_phi_fu_322_p4 = y76_0_reg_318;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        cross_X_ce0 = grp_my_filter_fx6_fu_384_data_out_V_ce0;
    end else begin
        cross_X_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        cross_X_we0 = grp_my_filter_fx6_fu_384_data_out_V_we0;
    end else begin
        cross_X_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        cross_Y_ce0 = grp_my_filter_fy5_fu_362_data_out_V_ce0;
    end else begin
        cross_Y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        cross_Y_we0 = grp_my_filter_fy5_fu_362_data_out_V_we0;
    end else begin
        cross_Y_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        f_V_address0 = grp_my_filter_fx6_fu_384_data_in_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        f_V_address0 = grp_my_filter_fy5_fu_362_data_in_V_address0;
    end else begin
        f_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        f_V_address1 = grp_my_filter_fx6_fu_384_data_in_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        f_V_address1 = grp_my_filter_fy5_fu_362_data_in_V_address1;
    end else begin
        f_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        f_V_ce0 = grp_my_filter_fx6_fu_384_data_in_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        f_V_ce0 = grp_my_filter_fy5_fu_362_data_in_V_ce0;
    end else begin
        f_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        f_V_ce1 = grp_my_filter_fx6_fu_384_data_in_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        f_V_ce1 = grp_my_filter_fy5_fu_362_data_in_V_ce1;
    end else begin
        f_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fx_V_address0 = grp_my_filter_fx6_fu_384_data_in_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fx_V_address0 = grp_my_filter_fx6_fu_384_data_out_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        fx_V_address0 = grp_my_filter_fy5_fu_369_data_in_V_address0;
    end else begin
        fx_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fx_V_address1 = grp_my_filter_fx6_fu_384_data_in_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        fx_V_address1 = grp_my_filter_fy5_fu_369_data_in_V_address1;
    end else begin
        fx_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fx_V_ce0 = grp_my_filter_fx6_fu_384_data_in_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fx_V_ce0 = grp_my_filter_fx6_fu_384_data_out_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        fx_V_ce0 = grp_my_filter_fy5_fu_369_data_in_V_ce0;
    end else begin
        fx_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fx_V_ce1 = grp_my_filter_fx6_fu_384_data_in_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        fx_V_ce1 = grp_my_filter_fy5_fu_369_data_in_V_ce1;
    end else begin
        fx_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fx_V_we0 = grp_my_filter_fx6_fu_384_data_out_V_we0;
    end else begin
        fx_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fxx_ce0 = grp_my_filter_fx6_fu_384_data_out_V_ce0;
    end else begin
        fxx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fxx_we0 = grp_my_filter_fx6_fu_384_data_out_V_we0;
    end else begin
        fxx_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fxy_ce0 = grp_my_filter_fy5_fu_369_data_out_V_ce0;
    end else begin
        fxy_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fxy_we0 = grp_my_filter_fy5_fu_369_data_out_V_we0;
    end else begin
        fxy_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fy_V_address0 = grp_my_filter_fy5_fu_362_data_in_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        fy_V_address0 = grp_my_filter_fy5_fu_362_data_out_V_address0;
    end else begin
        fy_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fy_V_ce0 = grp_my_filter_fy5_fu_362_data_in_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        fy_V_ce0 = grp_my_filter_fy5_fu_362_data_out_V_ce0;
    end else begin
        fy_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fy_V_ce1 = grp_my_filter_fy5_fu_362_data_in_V_ce1;
    end else begin
        fy_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fy_V_we0 = grp_my_filter_fy5_fu_362_data_out_V_we0;
    end else begin
        fy_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fyy_ce0 = grp_my_filter_fy5_fu_362_data_out_V_ce0;
    end else begin
        fyy_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fyy_we0 = grp_my_filter_fy5_fu_362_data_out_V_we0;
    end else begin
        fyy_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g1_V_address0 = zext_ln215_1_fu_464_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g1_V_address0 = grp_my_filter_fx6_fu_384_data_in_V_address0;
    end else begin
        g1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g1_V_address1 = g1_V_addr_reg_655;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g1_V_address1 = grp_my_filter_fx6_fu_384_data_in_V_address1;
    end else begin
        g1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        g1_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g1_V_ce0 = grp_my_filter_fx6_fu_384_data_in_V_ce0;
    end else begin
        g1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        g1_V_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g1_V_ce1 = grp_my_filter_fx6_fu_384_data_in_V_ce1;
    end else begin
        g1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln895_fu_489_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        g1_V_we1 = 1'b1;
    end else begin
        g1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g2_V_address0 = zext_ln215_1_fu_464_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g2_V_address0 = grp_my_filter_fy5_fu_362_data_in_V_address0;
    end else begin
        g2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g2_V_address1 = g2_V_addr_reg_661;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g2_V_address1 = grp_my_filter_fy5_fu_362_data_in_V_address1;
    end else begin
        g2_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        g2_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g2_V_ce0 = grp_my_filter_fy5_fu_362_data_in_V_ce0;
    end else begin
        g2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        g2_V_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g2_V_ce1 = grp_my_filter_fy5_fu_362_data_in_V_ce1;
    end else begin
        g2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln895_1_fu_505_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        g2_V_we1 = 1'b1;
    end else begin
        g2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g3_V_address0 = zext_ln215_1_fu_464_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g3_V_address0 = grp_my_filter_fx6_fu_392_data_in_V_address0;
    end else begin
        g3_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g3_V_address1 = g3_V_addr_reg_667;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g3_V_address1 = grp_my_filter_fx6_fu_392_data_in_V_address1;
    end else begin
        g3_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        g3_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g3_V_ce0 = grp_my_filter_fx6_fu_392_data_in_V_ce0;
    end else begin
        g3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        g3_V_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g3_V_ce1 = grp_my_filter_fx6_fu_392_data_in_V_ce1;
    end else begin
        g3_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln895_2_fu_521_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        g3_V_we1 = 1'b1;
    end else begin
        g3_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        g3x_V_address0 = grp_my_filter_fx6_fu_392_data_out_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        g3x_V_address0 = grp_my_filter_fx6_fu_384_data_in_V_address0;
    end else begin
        g3x_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        g3x_V_ce0 = grp_my_filter_fx6_fu_392_data_out_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        g3x_V_ce0 = grp_my_filter_fx6_fu_384_data_in_V_ce0;
    end else begin
        g3x_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        g3x_V_ce1 = grp_my_filter_fx6_fu_384_data_in_V_ce1;
    end else begin
        g3x_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        g3x_V_we0 = grp_my_filter_fx6_fu_392_data_out_V_we0;
    end else begin
        g3x_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g4_V_address0 = zext_ln215_1_fu_464_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g4_V_address0 = grp_my_filter_fy5_fu_369_data_in_V_address0;
    end else begin
        g4_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g4_V_address1 = g4_V_addr_reg_673;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g4_V_address1 = grp_my_filter_fy5_fu_369_data_in_V_address1;
    end else begin
        g4_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        g4_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g4_V_ce0 = grp_my_filter_fy5_fu_369_data_in_V_ce0;
    end else begin
        g4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        g4_V_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g4_V_ce1 = grp_my_filter_fy5_fu_369_data_in_V_ce1;
    end else begin
        g4_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln895_3_fu_537_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        g4_V_we1 = 1'b1;
    end else begin
        g4_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        g4y_V_address0 = grp_my_filter_fy5_fu_369_data_out_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        g4y_V_address0 = grp_my_filter_fy5_fu_362_data_in_V_address0;
    end else begin
        g4y_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        g4y_V_ce0 = grp_my_filter_fy5_fu_369_data_out_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        g4y_V_ce0 = grp_my_filter_fy5_fu_362_data_in_V_ce0;
    end else begin
        g4y_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        g4y_V_ce1 = grp_my_filter_fy5_fu_362_data_in_V_ce1;
    end else begin
        g4y_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        g4y_V_we0 = grp_my_filter_fy5_fu_369_data_out_V_we0;
    end else begin
        g4y_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g5_V_address0 = zext_ln215_1_fu_464_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        g5_V_address0 = grp_my_filter_fx6_fu_384_data_in_V_address0;
    end else begin
        g5_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        g5_V_address1 = g5_V_addr_reg_679;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        g5_V_address1 = grp_my_filter_fx6_fu_384_data_in_V_address1;
    end else begin
        g5_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        g5_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        g5_V_ce0 = grp_my_filter_fx6_fu_384_data_in_V_ce0;
    end else begin
        g5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        g5_V_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        g5_V_ce1 = grp_my_filter_fx6_fu_384_data_in_V_ce1;
    end else begin
        g5_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln895_4_fu_553_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        g5_V_we1 = 1'b1;
    end else begin
        g5_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        g5x_V_address0 = grp_my_filter_fx6_fu_384_data_out_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g5x_V_address0 = grp_my_filter_fy5_fu_375_data_in_V_address0;
    end else begin
        g5x_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        g5x_V_ce0 = grp_my_filter_fx6_fu_384_data_out_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        g5x_V_ce0 = grp_my_filter_fy5_fu_375_data_in_V_ce0;
    end else begin
        g5x_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        g5x_V_ce1 = grp_my_filter_fy5_fu_375_data_in_V_ce1;
    end else begin
        g5x_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        g5x_V_we0 = grp_my_filter_fx6_fu_384_data_out_V_we0;
    end else begin
        g5x_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        g6_V_ce0 = 1'b1;
    end else begin
        g6_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        g7_V_ce0 = 1'b1;
    end else begin
        g7_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_my_filter_fx6_fu_384_data_in_V_q0 = temp_cross6_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_my_filter_fx6_fu_384_data_in_V_q0 = g3x_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_filter_fx6_fu_384_data_in_V_q0 = g1_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_my_filter_fx6_fu_384_data_in_V_q0 = g5_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_my_filter_fx6_fu_384_data_in_V_q0 = fx_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_my_filter_fx6_fu_384_data_in_V_q0 = f_V_q0;
    end else begin
        grp_my_filter_fx6_fu_384_data_in_V_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_my_filter_fx6_fu_384_data_in_V_q1 = temp_cross6_V_q1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_my_filter_fx6_fu_384_data_in_V_q1 = g3x_V_q1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_filter_fx6_fu_384_data_in_V_q1 = g1_V_q1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_my_filter_fx6_fu_384_data_in_V_q1 = g5_V_q1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_my_filter_fx6_fu_384_data_in_V_q1 = fx_V_q1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_my_filter_fx6_fu_384_data_in_V_q1 = f_V_q1;
    end else begin
        grp_my_filter_fx6_fu_384_data_in_V_q1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_filter_fx6_fu_392_data_in_V_q0 = g3_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_my_filter_fx6_fu_392_data_in_V_q0 = adjChImg_V_q0;
    end else begin
        grp_my_filter_fx6_fu_392_data_in_V_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_filter_fx6_fu_392_data_in_V_q1 = g3_V_q1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_my_filter_fx6_fu_392_data_in_V_q1 = adjChImg_V_q1;
    end else begin
        grp_my_filter_fx6_fu_392_data_in_V_q1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_my_filter_fy5_fu_362_data_in_V_q0 = temp_cross7_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_my_filter_fy5_fu_362_data_in_V_q0 = g4y_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_filter_fy5_fu_362_data_in_V_q0 = g2_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_my_filter_fy5_fu_362_data_in_V_q0 = fy_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_my_filter_fy5_fu_362_data_in_V_q0 = f_V_q0;
    end else begin
        grp_my_filter_fy5_fu_362_data_in_V_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_my_filter_fy5_fu_362_data_in_V_q1 = temp_cross7_V_q1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_my_filter_fy5_fu_362_data_in_V_q1 = g4y_V_q1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_filter_fy5_fu_362_data_in_V_q1 = g2_V_q1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_my_filter_fy5_fu_362_data_in_V_q1 = fy_V_q1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_my_filter_fy5_fu_362_data_in_V_q1 = f_V_q1;
    end else begin
        grp_my_filter_fy5_fu_362_data_in_V_q1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_filter_fy5_fu_369_data_in_V_q0 = g4_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_my_filter_fy5_fu_369_data_in_V_q0 = fx_V_q0;
    end else begin
        grp_my_filter_fy5_fu_369_data_in_V_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_filter_fy5_fu_369_data_in_V_q1 = g4_V_q1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_my_filter_fy5_fu_369_data_in_V_q1 = fx_V_q1;
    end else begin
        grp_my_filter_fy5_fu_369_data_in_V_q1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_filter_fy5_fu_375_data_in_V_q0 = g5x_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_my_filter_fy5_fu_375_data_in_V_q0 = adjChImg_V_q0;
    end else begin
        grp_my_filter_fy5_fu_375_data_in_V_q0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_my_filter_fy5_fu_375_data_in_V_q1 = g5x_V_q1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_my_filter_fy5_fu_375_data_in_V_q1 = adjChImg_V_q1;
    end else begin
        grp_my_filter_fy5_fu_375_data_in_V_q1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        gx_ce0 = grp_my_filter_fx6_fu_384_data_out_V_ce0;
    end else begin
        gx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        gx_we0 = grp_my_filter_fx6_fu_384_data_out_V_we0;
    end else begin
        gx_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        gxx_ce0 = grp_my_filter_fx6_fu_384_data_out_V_ce0;
    end else begin
        gxx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        gxx_we0 = grp_my_filter_fx6_fu_384_data_out_V_we0;
    end else begin
        gxx_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        gxy_ce0 = grp_my_filter_fy5_fu_375_data_out_V_ce0;
    end else begin
        gxy_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        gxy_we0 = grp_my_filter_fy5_fu_375_data_out_V_we0;
    end else begin
        gxy_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        gy_ce0 = grp_my_filter_fy5_fu_362_data_out_V_ce0;
    end else begin
        gy_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        gy_we0 = grp_my_filter_fy5_fu_362_data_out_V_we0;
    end else begin
        gy_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        gyy_ce0 = grp_my_filter_fy5_fu_362_data_out_V_ce0;
    end else begin
        gyy_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        gyy_we0 = grp_my_filter_fy5_fu_362_data_out_V_we0;
    end else begin
        gyy_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_cross6_V_address0 = zext_ln215_3_reg_726;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        temp_cross6_V_address0 = grp_my_filter_fx6_fu_384_data_in_V_address0;
    end else begin
        temp_cross6_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_cross6_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        temp_cross6_V_ce0 = grp_my_filter_fx6_fu_384_data_in_V_ce0;
    end else begin
        temp_cross6_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        temp_cross6_V_ce1 = grp_my_filter_fx6_fu_384_data_in_V_ce1;
    end else begin
        temp_cross6_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_cross6_V_we0 = 1'b1;
    end else begin
        temp_cross6_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_cross7_V_address0 = zext_ln215_3_reg_726;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        temp_cross7_V_address0 = grp_my_filter_fy5_fu_362_data_in_V_address0;
    end else begin
        temp_cross7_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_cross7_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        temp_cross7_V_ce0 = grp_my_filter_fy5_fu_362_data_in_V_ce0;
    end else begin
        temp_cross7_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        temp_cross7_V_ce1 = grp_my_filter_fy5_fu_362_data_in_V_ce1;
    end else begin
        temp_cross7_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        temp_cross7_V_we0 = 1'b1;
    end else begin
        temp_cross7_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_my_filter_fx6_fu_384_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln126_fu_402_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln126_fu_402_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_my_filter_fx6_fu_384_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b0 == ap_block_state14_on_subcall_done) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln170_fu_559_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((1'b1 == ap_CS_fsm_state16) & (icmp_ln172_fu_583_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state18 : begin
            if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln126_fu_408_p2 = (indvar_flatten_reg_307 + 15'd1);

assign add_ln215_1_fu_599_p2 = (zext_ln172_reg_713 + zext_ln215_2_fu_595_p1);

assign add_ln215_fu_458_p2 = (zext_ln215_fu_454_p1 + zext_ln129_fu_450_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_on_subcall_done = ((grp_my_filter_fx6_fu_392_ap_done == 1'b0) | (grp_my_filter_fx6_fu_384_ap_done == 1'b0) | (grp_my_filter_fy5_fu_375_ap_done == 1'b0) | (grp_my_filter_fy5_fu_369_ap_done == 1'b0) | (grp_my_filter_fy5_fu_362_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state14_on_subcall_done = ((grp_my_filter_fx6_fu_384_ap_done == 1'b0) | (grp_my_filter_fy5_fu_362_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state18_on_subcall_done = ((grp_my_filter_fx6_fu_384_ap_done == 1'b0) | (grp_my_filter_fy5_fu_362_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_my_filter_fx6_fu_392_ap_done == 1'b0) | (grp_my_filter_fx6_fu_384_ap_done == 1'b0) | (grp_my_filter_fy5_fu_362_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state6_on_subcall_done = ((grp_my_filter_fy5_fu_375_ap_done == 1'b0) | (grp_my_filter_fy5_fu_369_ap_done == 1'b0) | (grp_my_filter_fy5_fu_362_ap_done == 1'b0));
end

assign ap_block_state7_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign g1_V_d1 = 8'd1;

assign g2_V_d1 = 8'd1;

assign g3_V_d1 = 8'd1;

assign g4_V_d1 = 8'd1;

assign g5_V_d1 = 8'd1;

assign g6_V_address0 = zext_ln215_3_fu_604_p1;

assign g7_V_address0 = zext_ln215_3_fu_604_p1;

assign grp_my_filter_fx6_fu_384_ap_start = grp_my_filter_fx6_fu_384_ap_start_reg;

assign grp_my_filter_fx6_fu_392_ap_start = grp_my_filter_fx6_fu_392_ap_start_reg;

assign grp_my_filter_fy5_fu_362_ap_start = grp_my_filter_fy5_fu_362_ap_start_reg;

assign grp_my_filter_fy5_fu_369_ap_start = grp_my_filter_fy5_fu_369_ap_start_reg;

assign grp_my_filter_fy5_fu_375_ap_start = grp_my_filter_fy5_fu_375_ap_start_reg;

assign icmp_ln126_fu_402_p2 = ((indvar_flatten_reg_307 == 15'd16384) ? 1'b1 : 1'b0);

assign icmp_ln128_fu_420_p2 = ((x77_0_reg_329 == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln170_fu_559_p2 = ((y95_0_reg_340 == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln172_fu_583_p2 = ((x96_0_reg_351 == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln895_1_fu_505_p2 = ((tmp_5_fu_495_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln895_2_fu_521_p2 = ((tmp_6_fu_511_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln895_3_fu_537_p2 = ((tmp_7_fu_527_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln895_4_fu_553_p2 = ((tmp_8_fu_543_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_489_p2 = ((tmp_2_fu_479_p4 == 7'd0) ? 1'b1 : 1'b0);

assign select_ln131_1_fu_434_p3 = ((icmp_ln128_fu_420_p2[0:0] === 1'b1) ? y_fu_414_p2 : ap_phi_mux_y76_0_phi_fu_322_p4);

assign select_ln131_fu_426_p3 = ((icmp_ln128_fu_420_p2[0:0] === 1'b1) ? 8'd0 : x77_0_reg_329);

assign select_ln209_1_fu_626_p3 = ((g7_V_q0[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign select_ln209_fu_611_p3 = ((g6_V_q0[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign temp_cross6_V_d0 = (select_ln209_fu_611_p3 & adjChImg_V_q0);

assign temp_cross7_V_d0 = (select_ln209_1_fu_626_p3 & adjChImg_V_q0);

assign tmp_1_fu_571_p3 = {{y95_0_reg_340}, {7'd0}};

assign tmp_2_fu_479_p4 = {{g1_V_q0[7:1]}};

assign tmp_5_fu_495_p4 = {{g2_V_q0[7:1]}};

assign tmp_6_fu_511_p4 = {{g3_V_q0[7:1]}};

assign tmp_7_fu_527_p4 = {{g4_V_q0[7:1]}};

assign tmp_8_fu_543_p4 = {{g5_V_q0[7:1]}};

assign tmp_fu_442_p3 = {{select_ln131_1_fu_434_p3}, {7'd0}};

assign x_1_fu_473_p2 = (select_ln131_fu_426_p3 + 8'd1);

assign x_fu_589_p2 = (x96_0_reg_351 + 8'd1);

assign y_1_fu_565_p2 = (y95_0_reg_340 + 8'd1);

assign y_fu_414_p2 = (ap_phi_mux_y76_0_phi_fu_322_p4 + 8'd1);

assign zext_ln129_fu_450_p1 = tmp_fu_442_p3;

assign zext_ln172_fu_579_p1 = tmp_1_fu_571_p3;

assign zext_ln215_1_fu_464_p1 = add_ln215_fu_458_p2;

assign zext_ln215_2_fu_595_p1 = x96_0_reg_351;

assign zext_ln215_3_fu_604_p1 = add_ln215_1_fu_599_p2;

assign zext_ln215_fu_454_p1 = select_ln131_fu_426_p3;

always @ (posedge ap_clk) begin
    zext_ln172_reg_713[6:0] <= 7'b0000000;
    zext_ln172_reg_713[15] <= 1'b0;
    zext_ln215_3_reg_726[63:16] <= 48'b000000000000000000000000000000000000000000000000;
end

endmodule //my_filter_v1
