// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "cross_channel_deblur.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic cross_channel_deblur::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic cross_channel_deblur::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<12> cross_channel_deblur::ap_ST_fsm_state1 = "1";
const sc_lv<12> cross_channel_deblur::ap_ST_fsm_state2 = "10";
const sc_lv<12> cross_channel_deblur::ap_ST_fsm_state3 = "100";
const sc_lv<12> cross_channel_deblur::ap_ST_fsm_state4 = "1000";
const sc_lv<12> cross_channel_deblur::ap_ST_fsm_state5 = "10000";
const sc_lv<12> cross_channel_deblur::ap_ST_fsm_state6 = "100000";
const sc_lv<12> cross_channel_deblur::ap_ST_fsm_state7 = "1000000";
const sc_lv<12> cross_channel_deblur::ap_ST_fsm_state8 = "10000000";
const sc_lv<12> cross_channel_deblur::ap_ST_fsm_state9 = "100000000";
const sc_lv<12> cross_channel_deblur::ap_ST_fsm_pp1_stage0 = "1000000000";
const sc_lv<12> cross_channel_deblur::ap_ST_fsm_state12 = "10000000000";
const sc_lv<12> cross_channel_deblur::ap_ST_fsm_state13 = "100000000000";
const sc_lv<32> cross_channel_deblur::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool cross_channel_deblur::ap_const_boolean_1 = true;
const sc_lv<32> cross_channel_deblur::ap_const_lv32_4 = "100";
const sc_lv<1> cross_channel_deblur::ap_const_lv1_0 = "0";
const sc_lv<32> cross_channel_deblur::ap_const_lv32_9 = "1001";
const bool cross_channel_deblur::ap_const_boolean_0 = false;
const sc_lv<32> cross_channel_deblur::ap_const_lv32_8 = "1000";
const sc_lv<1> cross_channel_deblur::ap_const_lv1_1 = "1";
const sc_lv<15> cross_channel_deblur::ap_const_lv15_0 = "000000000000000";
const sc_lv<32> cross_channel_deblur::ap_const_lv32_3 = "11";
const sc_lv<8> cross_channel_deblur::ap_const_lv8_0 = "00000000";
const sc_lv<32> cross_channel_deblur::ap_const_lv32_7 = "111";
const sc_lv<32> cross_channel_deblur::ap_const_lv32_5 = "101";
const sc_lv<32> cross_channel_deblur::ap_const_lv32_6 = "110";
const sc_lv<32> cross_channel_deblur::ap_const_lv32_2 = "10";
const sc_lv<32> cross_channel_deblur::ap_const_lv32_A = "1010";
const sc_lv<32> cross_channel_deblur::ap_const_lv32_1 = "1";
const sc_lv<32> cross_channel_deblur::ap_const_lv32_B = "1011";
const sc_lv<15> cross_channel_deblur::ap_const_lv15_4000 = "100000000000000";
const sc_lv<15> cross_channel_deblur::ap_const_lv15_1 = "1";
const sc_lv<8> cross_channel_deblur::ap_const_lv8_1 = "1";
const sc_lv<8> cross_channel_deblur::ap_const_lv8_80 = "10000000";
const sc_lv<7> cross_channel_deblur::ap_const_lv7_0 = "0000000";

cross_channel_deblur::cross_channel_deblur(sc_module_name name) : sc_module(name), mVcdFile(0) {
    x_bar_V_U = new cross_channel_debudo("x_bar_V_U");
    x_bar_V_U->clk(ap_clk);
    x_bar_V_U->reset(ap_rst);
    x_bar_V_U->address0(x_bar_V_address0);
    x_bar_V_U->ce0(x_bar_V_ce0);
    x_bar_V_U->we0(x_bar_V_we0);
    x_bar_V_U->d0(x_bar_V_d0);
    x_bar_V_U->q0(x_bar_V_q0);
    x_bar_V_U->address1(grp_my_filter_v1_fu_316_f_V_address1);
    x_bar_V_U->ce1(x_bar_V_ce1);
    x_bar_V_U->q1(x_bar_V_q1);
    x_old_V_U = new cross_channel_debvdy("x_old_V_U");
    x_old_V_U->clk(ap_clk);
    x_old_V_U->reset(ap_rst);
    x_old_V_U->address0(x_old_V_address0);
    x_old_V_U->ce0(x_old_V_ce0);
    x_old_V_U->we0(x_old_V_we0);
    x_old_V_U->d0(grp_array_copy_fu_330_data_out_V_d0);
    x_old_V_U->q0(x_old_V_q0);
    x_V_U = new cross_channel_debvdy("x_V_U");
    x_V_U->clk(ap_clk);
    x_V_U->reset(ap_rst);
    x_V_U->address0(x_V_address0);
    x_V_U->ce0(x_V_ce0);
    x_V_U->we0(x_V_we0);
    x_V_U->d0(grp_array_copy_fu_330_data_out_V_d0);
    x_V_U->q0(x_V_q0);
    y_1_V_U = new cross_channel_debxdS("y_1_V_U");
    y_1_V_U->clk(ap_clk);
    y_1_V_U->reset(ap_rst);
    y_1_V_U->address0(y_1_V_address0);
    y_1_V_U->ce0(y_1_V_ce0);
    y_1_V_U->we0(y_1_V_we0);
    y_1_V_U->d0(ap_var_for_const0);
    y_1_V_U->q0(y_1_V_q0);
    y_1_V_U->address1(grp_my_filter_v1_fu_316_g1_V_address1);
    y_1_V_U->ce1(y_1_V_ce1);
    y_1_V_U->we1(y_1_V_we1);
    y_1_V_U->d1(grp_my_filter_v1_fu_316_g1_V_d1);
    y_1_V_U->q1(y_1_V_q1);
    y_2_V_U = new cross_channel_debxdS("y_2_V_U");
    y_2_V_U->clk(ap_clk);
    y_2_V_U->reset(ap_rst);
    y_2_V_U->address0(y_2_V_address0);
    y_2_V_U->ce0(y_2_V_ce0);
    y_2_V_U->we0(y_2_V_we0);
    y_2_V_U->d0(ap_var_for_const0);
    y_2_V_U->q0(y_2_V_q0);
    y_2_V_U->address1(grp_my_filter_v1_fu_316_g2_V_address1);
    y_2_V_U->ce1(y_2_V_ce1);
    y_2_V_U->we1(y_2_V_we1);
    y_2_V_U->d1(grp_my_filter_v1_fu_316_g2_V_d1);
    y_2_V_U->q1(y_2_V_q1);
    y_3_V_U = new cross_channel_debxdS("y_3_V_U");
    y_3_V_U->clk(ap_clk);
    y_3_V_U->reset(ap_rst);
    y_3_V_U->address0(y_3_V_address0);
    y_3_V_U->ce0(y_3_V_ce0);
    y_3_V_U->we0(y_3_V_we0);
    y_3_V_U->d0(ap_var_for_const0);
    y_3_V_U->q0(y_3_V_q0);
    y_3_V_U->address1(grp_my_filter_v1_fu_316_g3_V_address1);
    y_3_V_U->ce1(y_3_V_ce1);
    y_3_V_U->we1(y_3_V_we1);
    y_3_V_U->d1(grp_my_filter_v1_fu_316_g3_V_d1);
    y_3_V_U->q1(y_3_V_q1);
    y_4_V_U = new cross_channel_debxdS("y_4_V_U");
    y_4_V_U->clk(ap_clk);
    y_4_V_U->reset(ap_rst);
    y_4_V_U->address0(y_4_V_address0);
    y_4_V_U->ce0(y_4_V_ce0);
    y_4_V_U->we0(y_4_V_we0);
    y_4_V_U->d0(ap_var_for_const0);
    y_4_V_U->q0(y_4_V_q0);
    y_4_V_U->address1(grp_my_filter_v1_fu_316_g4_V_address1);
    y_4_V_U->ce1(y_4_V_ce1);
    y_4_V_U->we1(y_4_V_we1);
    y_4_V_U->d1(grp_my_filter_v1_fu_316_g4_V_d1);
    y_4_V_U->q1(y_4_V_q1);
    y_5_V_U = new cross_channel_debxdS("y_5_V_U");
    y_5_V_U->clk(ap_clk);
    y_5_V_U->reset(ap_rst);
    y_5_V_U->address0(y_5_V_address0);
    y_5_V_U->ce0(y_5_V_ce0);
    y_5_V_U->we0(y_5_V_we0);
    y_5_V_U->d0(ap_var_for_const0);
    y_5_V_U->q0(y_5_V_q0);
    y_5_V_U->address1(grp_my_filter_v1_fu_316_g5_V_address1);
    y_5_V_U->ce1(y_5_V_ce1);
    y_5_V_U->we1(y_5_V_we1);
    y_5_V_U->d1(grp_my_filter_v1_fu_316_g5_V_d1);
    y_5_V_U->q1(y_5_V_q1);
    y_6_V_U = new cross_channel_debCeG("y_6_V_U");
    y_6_V_U->clk(ap_clk);
    y_6_V_U->reset(ap_rst);
    y_6_V_U->address0(y_6_V_address0);
    y_6_V_U->ce0(y_6_V_ce0);
    y_6_V_U->we0(y_6_V_we0);
    y_6_V_U->d0(ap_var_for_const1);
    y_6_V_U->q0(y_6_V_q0);
    y_7_V_U = new cross_channel_debCeG("y_7_V_U");
    y_7_V_U->clk(ap_clk);
    y_7_V_U->reset(ap_rst);
    y_7_V_U->address0(y_7_V_address0);
    y_7_V_U->ce0(y_7_V_ce0);
    y_7_V_U->we0(y_7_V_we0);
    y_7_V_U->d0(ap_var_for_const1);
    y_7_V_U->q0(y_7_V_q0);
    grp_ProxGS_fu_305 = new ProxGS("grp_ProxGS_fu_305");
    grp_ProxGS_fu_305->ap_clk(ap_clk);
    grp_ProxGS_fu_305->ap_rst(ap_rst);
    grp_ProxGS_fu_305->ap_start(grp_ProxGS_fu_305_ap_start);
    grp_ProxGS_fu_305->ap_done(grp_ProxGS_fu_305_ap_done);
    grp_ProxGS_fu_305->ap_idle(grp_ProxGS_fu_305_ap_idle);
    grp_ProxGS_fu_305->ap_ready(grp_ProxGS_fu_305_ap_ready);
    grp_ProxGS_fu_305->x_io_V_address0(grp_ProxGS_fu_305_x_io_V_address0);
    grp_ProxGS_fu_305->x_io_V_ce0(grp_ProxGS_fu_305_x_io_V_ce0);
    grp_ProxGS_fu_305->x_io_V_we0(grp_ProxGS_fu_305_x_io_V_we0);
    grp_ProxGS_fu_305->x_io_V_d0(grp_ProxGS_fu_305_x_io_V_d0);
    grp_ProxGS_fu_305->x_io_V_q0(x_bar_V_q0);
    grp_ProxGS_fu_305->coe_a_M_real_address0(grp_ProxGS_fu_305_coe_a_M_real_address0);
    grp_ProxGS_fu_305->coe_a_M_real_ce0(grp_ProxGS_fu_305_coe_a_M_real_ce0);
    grp_ProxGS_fu_305->coe_a_M_real_q0(coe_a_M_real_q0);
    grp_ProxGS_fu_305->coe_a_M_imag_address0(grp_ProxGS_fu_305_coe_a_M_imag_address0);
    grp_ProxGS_fu_305->coe_a_M_imag_ce0(grp_ProxGS_fu_305_coe_a_M_imag_ce0);
    grp_ProxGS_fu_305->coe_a_M_imag_q0(coe_a_M_imag_q0);
    grp_ProxGS_fu_305->coe_b_address0(grp_ProxGS_fu_305_coe_b_address0);
    grp_ProxGS_fu_305->coe_b_ce0(grp_ProxGS_fu_305_coe_b_ce0);
    grp_ProxGS_fu_305->coe_b_q0(coe_b_q0);
    grp_my_filter_v1_fu_316 = new my_filter_v1("grp_my_filter_v1_fu_316");
    grp_my_filter_v1_fu_316->ap_clk(ap_clk);
    grp_my_filter_v1_fu_316->ap_rst(ap_rst);
    grp_my_filter_v1_fu_316->ap_start(grp_my_filter_v1_fu_316_ap_start);
    grp_my_filter_v1_fu_316->ap_done(grp_my_filter_v1_fu_316_ap_done);
    grp_my_filter_v1_fu_316->ap_idle(grp_my_filter_v1_fu_316_ap_idle);
    grp_my_filter_v1_fu_316->ap_ready(grp_my_filter_v1_fu_316_ap_ready);
    grp_my_filter_v1_fu_316->f_V_address0(grp_my_filter_v1_fu_316_f_V_address0);
    grp_my_filter_v1_fu_316->f_V_ce0(grp_my_filter_v1_fu_316_f_V_ce0);
    grp_my_filter_v1_fu_316->f_V_q0(x_bar_V_q0);
    grp_my_filter_v1_fu_316->f_V_address1(grp_my_filter_v1_fu_316_f_V_address1);
    grp_my_filter_v1_fu_316->f_V_ce1(grp_my_filter_v1_fu_316_f_V_ce1);
    grp_my_filter_v1_fu_316->f_V_q1(x_bar_V_q1);
    grp_my_filter_v1_fu_316->adjChImg_V_address0(grp_my_filter_v1_fu_316_adjChImg_V_address0);
    grp_my_filter_v1_fu_316->adjChImg_V_ce0(grp_my_filter_v1_fu_316_adjChImg_V_ce0);
    grp_my_filter_v1_fu_316->adjChImg_V_q0(adjChImg_V_q0);
    grp_my_filter_v1_fu_316->adjChImg_V_address1(grp_my_filter_v1_fu_316_adjChImg_V_address1);
    grp_my_filter_v1_fu_316->adjChImg_V_ce1(grp_my_filter_v1_fu_316_adjChImg_V_ce1);
    grp_my_filter_v1_fu_316->adjChImg_V_q1(adjChImg_V_q1);
    grp_my_filter_v1_fu_316->g1_V_address0(grp_my_filter_v1_fu_316_g1_V_address0);
    grp_my_filter_v1_fu_316->g1_V_ce0(grp_my_filter_v1_fu_316_g1_V_ce0);
    grp_my_filter_v1_fu_316->g1_V_q0(y_1_V_q0);
    grp_my_filter_v1_fu_316->g1_V_address1(grp_my_filter_v1_fu_316_g1_V_address1);
    grp_my_filter_v1_fu_316->g1_V_ce1(grp_my_filter_v1_fu_316_g1_V_ce1);
    grp_my_filter_v1_fu_316->g1_V_we1(grp_my_filter_v1_fu_316_g1_V_we1);
    grp_my_filter_v1_fu_316->g1_V_d1(grp_my_filter_v1_fu_316_g1_V_d1);
    grp_my_filter_v1_fu_316->g1_V_q1(y_1_V_q1);
    grp_my_filter_v1_fu_316->g2_V_address0(grp_my_filter_v1_fu_316_g2_V_address0);
    grp_my_filter_v1_fu_316->g2_V_ce0(grp_my_filter_v1_fu_316_g2_V_ce0);
    grp_my_filter_v1_fu_316->g2_V_q0(y_2_V_q0);
    grp_my_filter_v1_fu_316->g2_V_address1(grp_my_filter_v1_fu_316_g2_V_address1);
    grp_my_filter_v1_fu_316->g2_V_ce1(grp_my_filter_v1_fu_316_g2_V_ce1);
    grp_my_filter_v1_fu_316->g2_V_we1(grp_my_filter_v1_fu_316_g2_V_we1);
    grp_my_filter_v1_fu_316->g2_V_d1(grp_my_filter_v1_fu_316_g2_V_d1);
    grp_my_filter_v1_fu_316->g2_V_q1(y_2_V_q1);
    grp_my_filter_v1_fu_316->g3_V_address0(grp_my_filter_v1_fu_316_g3_V_address0);
    grp_my_filter_v1_fu_316->g3_V_ce0(grp_my_filter_v1_fu_316_g3_V_ce0);
    grp_my_filter_v1_fu_316->g3_V_q0(y_3_V_q0);
    grp_my_filter_v1_fu_316->g3_V_address1(grp_my_filter_v1_fu_316_g3_V_address1);
    grp_my_filter_v1_fu_316->g3_V_ce1(grp_my_filter_v1_fu_316_g3_V_ce1);
    grp_my_filter_v1_fu_316->g3_V_we1(grp_my_filter_v1_fu_316_g3_V_we1);
    grp_my_filter_v1_fu_316->g3_V_d1(grp_my_filter_v1_fu_316_g3_V_d1);
    grp_my_filter_v1_fu_316->g3_V_q1(y_3_V_q1);
    grp_my_filter_v1_fu_316->g4_V_address0(grp_my_filter_v1_fu_316_g4_V_address0);
    grp_my_filter_v1_fu_316->g4_V_ce0(grp_my_filter_v1_fu_316_g4_V_ce0);
    grp_my_filter_v1_fu_316->g4_V_q0(y_4_V_q0);
    grp_my_filter_v1_fu_316->g4_V_address1(grp_my_filter_v1_fu_316_g4_V_address1);
    grp_my_filter_v1_fu_316->g4_V_ce1(grp_my_filter_v1_fu_316_g4_V_ce1);
    grp_my_filter_v1_fu_316->g4_V_we1(grp_my_filter_v1_fu_316_g4_V_we1);
    grp_my_filter_v1_fu_316->g4_V_d1(grp_my_filter_v1_fu_316_g4_V_d1);
    grp_my_filter_v1_fu_316->g4_V_q1(y_4_V_q1);
    grp_my_filter_v1_fu_316->g5_V_address0(grp_my_filter_v1_fu_316_g5_V_address0);
    grp_my_filter_v1_fu_316->g5_V_ce0(grp_my_filter_v1_fu_316_g5_V_ce0);
    grp_my_filter_v1_fu_316->g5_V_q0(y_5_V_q0);
    grp_my_filter_v1_fu_316->g5_V_address1(grp_my_filter_v1_fu_316_g5_V_address1);
    grp_my_filter_v1_fu_316->g5_V_ce1(grp_my_filter_v1_fu_316_g5_V_ce1);
    grp_my_filter_v1_fu_316->g5_V_we1(grp_my_filter_v1_fu_316_g5_V_we1);
    grp_my_filter_v1_fu_316->g5_V_d1(grp_my_filter_v1_fu_316_g5_V_d1);
    grp_my_filter_v1_fu_316->g5_V_q1(y_5_V_q1);
    grp_my_filter_v1_fu_316->g6_V_address0(grp_my_filter_v1_fu_316_g6_V_address0);
    grp_my_filter_v1_fu_316->g6_V_ce0(grp_my_filter_v1_fu_316_g6_V_ce0);
    grp_my_filter_v1_fu_316->g6_V_q0(y_6_V_q0);
    grp_my_filter_v1_fu_316->g7_V_address0(grp_my_filter_v1_fu_316_g7_V_address0);
    grp_my_filter_v1_fu_316->g7_V_ce0(grp_my_filter_v1_fu_316_g7_V_ce0);
    grp_my_filter_v1_fu_316->g7_V_q0(y_7_V_q0);
    grp_array_copy_fu_330 = new array_copy("grp_array_copy_fu_330");
    grp_array_copy_fu_330->ap_clk(ap_clk);
    grp_array_copy_fu_330->ap_rst(ap_rst);
    grp_array_copy_fu_330->ap_start(grp_array_copy_fu_330_ap_start);
    grp_array_copy_fu_330->ap_done(grp_array_copy_fu_330_ap_done);
    grp_array_copy_fu_330->ap_idle(grp_array_copy_fu_330_ap_idle);
    grp_array_copy_fu_330->ap_ready(grp_array_copy_fu_330_ap_ready);
    grp_array_copy_fu_330->data_in_V_address0(grp_array_copy_fu_330_data_in_V_address0);
    grp_array_copy_fu_330->data_in_V_ce0(grp_array_copy_fu_330_data_in_V_ce0);
    grp_array_copy_fu_330->data_in_V_q0(grp_array_copy_fu_330_data_in_V_q0);
    grp_array_copy_fu_330->data_out_V_address0(grp_array_copy_fu_330_data_out_V_address0);
    grp_array_copy_fu_330->data_out_V_ce0(grp_array_copy_fu_330_data_out_V_ce0);
    grp_array_copy_fu_330->data_out_V_we0(grp_array_copy_fu_330_data_out_V_we0);
    grp_array_copy_fu_330->data_out_V_d0(grp_array_copy_fu_330_data_out_V_d0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Img_V_address0);
    sensitive << ( grp_array_copy_fu_330_data_in_V_address0 );
    sensitive << ( grp_array_copy_fu_330_data_out_V_address0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_Img_V_ce0);
    sensitive << ( grp_array_copy_fu_330_data_in_V_ce0 );
    sensitive << ( grp_array_copy_fu_330_data_out_V_ce0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_Img_V_d0);
    sensitive << ( grp_array_copy_fu_330_data_out_V_d0 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_Img_V_we0);
    sensitive << ( grp_array_copy_fu_330_data_out_V_we0 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_add_ln213_fu_424_p2);
    sensitive << ( indvar_flatten11_reg_272 );

    SC_METHOD(thread_add_ln321_1_fu_474_p2);
    sensitive << ( zext_ln321_4_fu_470_p1 );
    sensitive << ( zext_ln216_fu_466_p1 );

    SC_METHOD(thread_add_ln321_fu_395_p2);
    sensitive << ( zext_ln321_fu_391_p1 );
    sensitive << ( zext_ln44_fu_387_p1 );

    SC_METHOD(thread_add_ln41_fu_345_p2);
    sensitive << ( indvar_flatten_reg_239 );

    SC_METHOD(thread_adjChImg_V_address0);
    sensitive << ( grp_my_filter_v1_fu_316_adjChImg_V_address0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_adjChImg_V_address1);
    sensitive << ( grp_my_filter_v1_fu_316_adjChImg_V_address1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_adjChImg_V_ce0);
    sensitive << ( grp_my_filter_v1_fu_316_adjChImg_V_ce0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_adjChImg_V_ce1);
    sensitive << ( grp_my_filter_v1_fu_316_adjChImg_V_ce1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_11001);

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);

    SC_METHOD(thread_ap_block_state10_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state11_pp1_stage0_iter1);

    SC_METHOD(thread_ap_block_state7_on_subcall_done);
    sensitive << ( grp_my_filter_v1_fu_316_ap_done );
    sensitive << ( grp_array_copy_fu_330_ap_done );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state10);
    sensitive << ( icmp_ln213_fu_418_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( grp_array_copy_fu_330_ap_done );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_ap_phi_mux_j_0_i_phi_fu_287_p4);
    sensitive << ( j_0_i_reg_283 );
    sensitive << ( icmp_ln213_reg_517 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( select_ln218_1_reg_526 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_array_copy_fu_330_ap_done );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_coe_a_M_imag_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( grp_ProxGS_fu_305_coe_a_M_imag_address0 );

    SC_METHOD(thread_coe_a_M_imag_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( grp_ProxGS_fu_305_coe_a_M_imag_ce0 );

    SC_METHOD(thread_coe_a_M_real_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( grp_ProxGS_fu_305_coe_a_M_real_address0 );

    SC_METHOD(thread_coe_a_M_real_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( grp_ProxGS_fu_305_coe_a_M_real_ce0 );

    SC_METHOD(thread_coe_b_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( grp_ProxGS_fu_305_coe_b_address0 );

    SC_METHOD(thread_coe_b_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( grp_ProxGS_fu_305_coe_b_ce0 );

    SC_METHOD(thread_grp_ProxGS_fu_305_ap_start);
    sensitive << ( grp_ProxGS_fu_305_ap_start_reg );

    SC_METHOD(thread_grp_array_copy_fu_330_ap_start);
    sensitive << ( grp_array_copy_fu_330_ap_start_reg );

    SC_METHOD(thread_grp_array_copy_fu_330_data_in_V_q0);
    sensitive << ( Img_V_q0 );
    sensitive << ( x_V_q0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_grp_my_filter_v1_fu_316_ap_start);
    sensitive << ( grp_my_filter_v1_fu_316_ap_start_reg );

    SC_METHOD(thread_i_fu_486_p2);
    sensitive << ( select_ln218_fu_442_p3 );

    SC_METHOD(thread_icmp_ln213_fu_418_p2);
    sensitive << ( indvar_flatten11_reg_272 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_icmp_ln215_fu_436_p2);
    sensitive << ( i_0_i_reg_294 );
    sensitive << ( icmp_ln213_fu_418_p2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_icmp_ln41_fu_339_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( indvar_flatten_reg_239 );

    SC_METHOD(thread_icmp_ln43_fu_357_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln41_fu_339_p2 );
    sensitive << ( x_0_i_reg_261 );

    SC_METHOD(thread_j_fu_430_p2);
    sensitive << ( ap_phi_mux_j_0_i_phi_fu_287_p4 );

    SC_METHOD(thread_select_ln218_1_fu_450_p3);
    sensitive << ( ap_phi_mux_j_0_i_phi_fu_287_p4 );
    sensitive << ( icmp_ln215_fu_436_p2 );
    sensitive << ( j_fu_430_p2 );

    SC_METHOD(thread_select_ln218_fu_442_p3);
    sensitive << ( i_0_i_reg_294 );
    sensitive << ( icmp_ln215_fu_436_p2 );

    SC_METHOD(thread_select_ln46_1_fu_371_p3);
    sensitive << ( y_0_i_reg_250 );
    sensitive << ( icmp_ln43_fu_357_p2 );
    sensitive << ( y_fu_351_p2 );

    SC_METHOD(thread_select_ln46_fu_363_p3);
    sensitive << ( x_0_i_reg_261 );
    sensitive << ( icmp_ln43_fu_357_p2 );

    SC_METHOD(thread_sub_ln214_fu_492_p2);
    sensitive << ( x_old_V_q0 );
    sensitive << ( x_V_q0 );

    SC_METHOD(thread_tmp_6_fu_458_p3);
    sensitive << ( select_ln218_1_fu_450_p3 );

    SC_METHOD(thread_tmp_fu_379_p3);
    sensitive << ( select_ln46_1_fu_371_p3 );

    SC_METHOD(thread_x_V_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( zext_ln321_5_fu_480_p1 );
    sensitive << ( grp_array_copy_fu_330_data_in_V_address0 );
    sensitive << ( grp_array_copy_fu_330_data_out_V_address0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_x_V_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( grp_array_copy_fu_330_data_in_V_ce0 );
    sensitive << ( grp_array_copy_fu_330_data_out_V_ce0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_x_V_we0);
    sensitive << ( grp_array_copy_fu_330_data_out_V_we0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_x_bar_V_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( zext_ln321_5_reg_531 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( grp_ProxGS_fu_305_x_io_V_address0 );
    sensitive << ( grp_my_filter_v1_fu_316_f_V_address0 );
    sensitive << ( grp_array_copy_fu_330_data_out_V_address0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_x_bar_V_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( grp_ProxGS_fu_305_x_io_V_ce0 );
    sensitive << ( grp_my_filter_v1_fu_316_f_V_ce0 );
    sensitive << ( grp_array_copy_fu_330_data_out_V_ce0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_x_bar_V_ce1);
    sensitive << ( grp_my_filter_v1_fu_316_f_V_ce1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_x_bar_V_d0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( grp_ProxGS_fu_305_x_io_V_d0 );
    sensitive << ( grp_array_copy_fu_330_data_out_V_d0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( sub_ln214_fu_492_p2 );

    SC_METHOD(thread_x_bar_V_we0);
    sensitive << ( icmp_ln213_reg_517 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( grp_ProxGS_fu_305_x_io_V_we0 );
    sensitive << ( grp_array_copy_fu_330_data_out_V_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_x_fu_412_p2);
    sensitive << ( select_ln46_fu_363_p3 );

    SC_METHOD(thread_x_old_V_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( zext_ln321_5_fu_480_p1 );
    sensitive << ( grp_array_copy_fu_330_data_out_V_address0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_x_old_V_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( grp_array_copy_fu_330_data_out_V_ce0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_x_old_V_we0);
    sensitive << ( grp_array_copy_fu_330_data_out_V_we0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_1_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_my_filter_v1_fu_316_g1_V_address0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln321_3_fu_401_p1 );

    SC_METHOD(thread_y_1_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_my_filter_v1_fu_316_g1_V_ce0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_1_V_ce1);
    sensitive << ( grp_my_filter_v1_fu_316_g1_V_ce1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_1_V_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln41_fu_339_p2 );

    SC_METHOD(thread_y_1_V_we1);
    sensitive << ( grp_my_filter_v1_fu_316_g1_V_we1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_2_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_my_filter_v1_fu_316_g2_V_address0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln321_3_fu_401_p1 );

    SC_METHOD(thread_y_2_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_my_filter_v1_fu_316_g2_V_ce0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_2_V_ce1);
    sensitive << ( grp_my_filter_v1_fu_316_g2_V_ce1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_2_V_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln41_fu_339_p2 );

    SC_METHOD(thread_y_2_V_we1);
    sensitive << ( grp_my_filter_v1_fu_316_g2_V_we1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_3_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_my_filter_v1_fu_316_g3_V_address0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln321_3_fu_401_p1 );

    SC_METHOD(thread_y_3_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_my_filter_v1_fu_316_g3_V_ce0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_3_V_ce1);
    sensitive << ( grp_my_filter_v1_fu_316_g3_V_ce1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_3_V_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln41_fu_339_p2 );

    SC_METHOD(thread_y_3_V_we1);
    sensitive << ( grp_my_filter_v1_fu_316_g3_V_we1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_4_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_my_filter_v1_fu_316_g4_V_address0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln321_3_fu_401_p1 );

    SC_METHOD(thread_y_4_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_my_filter_v1_fu_316_g4_V_ce0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_4_V_ce1);
    sensitive << ( grp_my_filter_v1_fu_316_g4_V_ce1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_4_V_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln41_fu_339_p2 );

    SC_METHOD(thread_y_4_V_we1);
    sensitive << ( grp_my_filter_v1_fu_316_g4_V_we1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_5_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_my_filter_v1_fu_316_g5_V_address0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln321_3_fu_401_p1 );

    SC_METHOD(thread_y_5_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_my_filter_v1_fu_316_g5_V_ce0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_5_V_ce1);
    sensitive << ( grp_my_filter_v1_fu_316_g5_V_ce1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_5_V_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln41_fu_339_p2 );

    SC_METHOD(thread_y_5_V_we1);
    sensitive << ( grp_my_filter_v1_fu_316_g5_V_we1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_6_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_my_filter_v1_fu_316_g6_V_address0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln321_3_fu_401_p1 );

    SC_METHOD(thread_y_6_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_my_filter_v1_fu_316_g6_V_ce0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_6_V_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln41_fu_339_p2 );

    SC_METHOD(thread_y_7_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_my_filter_v1_fu_316_g7_V_address0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln321_3_fu_401_p1 );

    SC_METHOD(thread_y_7_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_my_filter_v1_fu_316_g7_V_ce0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_y_7_V_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln41_fu_339_p2 );

    SC_METHOD(thread_y_fu_351_p2);
    sensitive << ( y_0_i_reg_250 );

    SC_METHOD(thread_zext_ln216_fu_466_p1);
    sensitive << ( tmp_6_fu_458_p3 );

    SC_METHOD(thread_zext_ln321_3_fu_401_p1);
    sensitive << ( add_ln321_fu_395_p2 );

    SC_METHOD(thread_zext_ln321_4_fu_470_p1);
    sensitive << ( select_ln218_fu_442_p3 );

    SC_METHOD(thread_zext_ln321_5_fu_480_p1);
    sensitive << ( add_ln321_1_fu_474_p2 );

    SC_METHOD(thread_zext_ln321_fu_391_p1);
    sensitive << ( select_ln46_fu_363_p3 );

    SC_METHOD(thread_zext_ln44_fu_387_p1);
    sensitive << ( tmp_fu_379_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln41_fu_339_p2 );
    sensitive << ( icmp_ln213_fu_418_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( grp_ProxGS_fu_305_ap_done );
    sensitive << ( ap_block_pp1_stage0_subdone );
    sensitive << ( grp_array_copy_fu_330_ap_done );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_block_state7_on_subcall_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000001";
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    grp_ProxGS_fu_305_ap_start_reg = SC_LOGIC_0;
    grp_my_filter_v1_fu_316_ap_start_reg = SC_LOGIC_0;
    grp_array_copy_fu_330_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "cross_channel_deblur_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, Img_V_address0, "(port)Img_V_address0");
    sc_trace(mVcdFile, Img_V_ce0, "(port)Img_V_ce0");
    sc_trace(mVcdFile, Img_V_we0, "(port)Img_V_we0");
    sc_trace(mVcdFile, Img_V_d0, "(port)Img_V_d0");
    sc_trace(mVcdFile, Img_V_q0, "(port)Img_V_q0");
    sc_trace(mVcdFile, adjChImg_V_address0, "(port)adjChImg_V_address0");
    sc_trace(mVcdFile, adjChImg_V_ce0, "(port)adjChImg_V_ce0");
    sc_trace(mVcdFile, adjChImg_V_q0, "(port)adjChImg_V_q0");
    sc_trace(mVcdFile, adjChImg_V_address1, "(port)adjChImg_V_address1");
    sc_trace(mVcdFile, adjChImg_V_ce1, "(port)adjChImg_V_ce1");
    sc_trace(mVcdFile, adjChImg_V_q1, "(port)adjChImg_V_q1");
    sc_trace(mVcdFile, coe_a_M_real_address0, "(port)coe_a_M_real_address0");
    sc_trace(mVcdFile, coe_a_M_real_ce0, "(port)coe_a_M_real_ce0");
    sc_trace(mVcdFile, coe_a_M_real_q0, "(port)coe_a_M_real_q0");
    sc_trace(mVcdFile, coe_a_M_imag_address0, "(port)coe_a_M_imag_address0");
    sc_trace(mVcdFile, coe_a_M_imag_ce0, "(port)coe_a_M_imag_ce0");
    sc_trace(mVcdFile, coe_a_M_imag_q0, "(port)coe_a_M_imag_q0");
    sc_trace(mVcdFile, coe_b_address0, "(port)coe_b_address0");
    sc_trace(mVcdFile, coe_b_ce0, "(port)coe_b_ce0");
    sc_trace(mVcdFile, coe_b_q0, "(port)coe_b_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten11_reg_272, "indvar_flatten11_reg_272");
    sc_trace(mVcdFile, j_0_i_reg_283, "j_0_i_reg_283");
    sc_trace(mVcdFile, i_0_i_reg_294, "i_0_i_reg_294");
    sc_trace(mVcdFile, add_ln41_fu_345_p2, "add_ln41_fu_345_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, select_ln46_1_fu_371_p3, "select_ln46_1_fu_371_p3");
    sc_trace(mVcdFile, icmp_ln41_fu_339_p2, "icmp_ln41_fu_339_p2");
    sc_trace(mVcdFile, x_fu_412_p2, "x_fu_412_p2");
    sc_trace(mVcdFile, icmp_ln213_fu_418_p2, "icmp_ln213_fu_418_p2");
    sc_trace(mVcdFile, icmp_ln213_reg_517, "icmp_ln213_reg_517");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_block_state10_pp1_stage0_iter0, "ap_block_state10_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state11_pp1_stage0_iter1, "ap_block_state11_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, add_ln213_fu_424_p2, "add_ln213_fu_424_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, select_ln218_1_fu_450_p3, "select_ln218_1_fu_450_p3");
    sc_trace(mVcdFile, select_ln218_1_reg_526, "select_ln218_1_reg_526");
    sc_trace(mVcdFile, zext_ln321_5_fu_480_p1, "zext_ln321_5_fu_480_p1");
    sc_trace(mVcdFile, zext_ln321_5_reg_531, "zext_ln321_5_reg_531");
    sc_trace(mVcdFile, i_fu_486_p2, "i_fu_486_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, grp_ProxGS_fu_305_ap_ready, "grp_ProxGS_fu_305_ap_ready");
    sc_trace(mVcdFile, grp_ProxGS_fu_305_ap_done, "grp_ProxGS_fu_305_ap_done");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state10, "ap_condition_pp1_exit_iter0_state10");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, x_bar_V_address0, "x_bar_V_address0");
    sc_trace(mVcdFile, x_bar_V_ce0, "x_bar_V_ce0");
    sc_trace(mVcdFile, x_bar_V_we0, "x_bar_V_we0");
    sc_trace(mVcdFile, x_bar_V_d0, "x_bar_V_d0");
    sc_trace(mVcdFile, x_bar_V_q0, "x_bar_V_q0");
    sc_trace(mVcdFile, x_bar_V_ce1, "x_bar_V_ce1");
    sc_trace(mVcdFile, x_bar_V_q1, "x_bar_V_q1");
    sc_trace(mVcdFile, x_old_V_address0, "x_old_V_address0");
    sc_trace(mVcdFile, x_old_V_ce0, "x_old_V_ce0");
    sc_trace(mVcdFile, x_old_V_we0, "x_old_V_we0");
    sc_trace(mVcdFile, x_old_V_q0, "x_old_V_q0");
    sc_trace(mVcdFile, x_V_address0, "x_V_address0");
    sc_trace(mVcdFile, x_V_ce0, "x_V_ce0");
    sc_trace(mVcdFile, x_V_we0, "x_V_we0");
    sc_trace(mVcdFile, x_V_q0, "x_V_q0");
    sc_trace(mVcdFile, y_1_V_address0, "y_1_V_address0");
    sc_trace(mVcdFile, y_1_V_ce0, "y_1_V_ce0");
    sc_trace(mVcdFile, y_1_V_we0, "y_1_V_we0");
    sc_trace(mVcdFile, y_1_V_q0, "y_1_V_q0");
    sc_trace(mVcdFile, y_1_V_ce1, "y_1_V_ce1");
    sc_trace(mVcdFile, y_1_V_we1, "y_1_V_we1");
    sc_trace(mVcdFile, y_1_V_q1, "y_1_V_q1");
    sc_trace(mVcdFile, y_2_V_address0, "y_2_V_address0");
    sc_trace(mVcdFile, y_2_V_ce0, "y_2_V_ce0");
    sc_trace(mVcdFile, y_2_V_we0, "y_2_V_we0");
    sc_trace(mVcdFile, y_2_V_q0, "y_2_V_q0");
    sc_trace(mVcdFile, y_2_V_ce1, "y_2_V_ce1");
    sc_trace(mVcdFile, y_2_V_we1, "y_2_V_we1");
    sc_trace(mVcdFile, y_2_V_q1, "y_2_V_q1");
    sc_trace(mVcdFile, y_3_V_address0, "y_3_V_address0");
    sc_trace(mVcdFile, y_3_V_ce0, "y_3_V_ce0");
    sc_trace(mVcdFile, y_3_V_we0, "y_3_V_we0");
    sc_trace(mVcdFile, y_3_V_q0, "y_3_V_q0");
    sc_trace(mVcdFile, y_3_V_ce1, "y_3_V_ce1");
    sc_trace(mVcdFile, y_3_V_we1, "y_3_V_we1");
    sc_trace(mVcdFile, y_3_V_q1, "y_3_V_q1");
    sc_trace(mVcdFile, y_4_V_address0, "y_4_V_address0");
    sc_trace(mVcdFile, y_4_V_ce0, "y_4_V_ce0");
    sc_trace(mVcdFile, y_4_V_we0, "y_4_V_we0");
    sc_trace(mVcdFile, y_4_V_q0, "y_4_V_q0");
    sc_trace(mVcdFile, y_4_V_ce1, "y_4_V_ce1");
    sc_trace(mVcdFile, y_4_V_we1, "y_4_V_we1");
    sc_trace(mVcdFile, y_4_V_q1, "y_4_V_q1");
    sc_trace(mVcdFile, y_5_V_address0, "y_5_V_address0");
    sc_trace(mVcdFile, y_5_V_ce0, "y_5_V_ce0");
    sc_trace(mVcdFile, y_5_V_we0, "y_5_V_we0");
    sc_trace(mVcdFile, y_5_V_q0, "y_5_V_q0");
    sc_trace(mVcdFile, y_5_V_ce1, "y_5_V_ce1");
    sc_trace(mVcdFile, y_5_V_we1, "y_5_V_we1");
    sc_trace(mVcdFile, y_5_V_q1, "y_5_V_q1");
    sc_trace(mVcdFile, y_6_V_address0, "y_6_V_address0");
    sc_trace(mVcdFile, y_6_V_ce0, "y_6_V_ce0");
    sc_trace(mVcdFile, y_6_V_we0, "y_6_V_we0");
    sc_trace(mVcdFile, y_6_V_q0, "y_6_V_q0");
    sc_trace(mVcdFile, y_7_V_address0, "y_7_V_address0");
    sc_trace(mVcdFile, y_7_V_ce0, "y_7_V_ce0");
    sc_trace(mVcdFile, y_7_V_we0, "y_7_V_we0");
    sc_trace(mVcdFile, y_7_V_q0, "y_7_V_q0");
    sc_trace(mVcdFile, grp_ProxGS_fu_305_ap_start, "grp_ProxGS_fu_305_ap_start");
    sc_trace(mVcdFile, grp_ProxGS_fu_305_ap_idle, "grp_ProxGS_fu_305_ap_idle");
    sc_trace(mVcdFile, grp_ProxGS_fu_305_x_io_V_address0, "grp_ProxGS_fu_305_x_io_V_address0");
    sc_trace(mVcdFile, grp_ProxGS_fu_305_x_io_V_ce0, "grp_ProxGS_fu_305_x_io_V_ce0");
    sc_trace(mVcdFile, grp_ProxGS_fu_305_x_io_V_we0, "grp_ProxGS_fu_305_x_io_V_we0");
    sc_trace(mVcdFile, grp_ProxGS_fu_305_x_io_V_d0, "grp_ProxGS_fu_305_x_io_V_d0");
    sc_trace(mVcdFile, grp_ProxGS_fu_305_coe_a_M_real_address0, "grp_ProxGS_fu_305_coe_a_M_real_address0");
    sc_trace(mVcdFile, grp_ProxGS_fu_305_coe_a_M_real_ce0, "grp_ProxGS_fu_305_coe_a_M_real_ce0");
    sc_trace(mVcdFile, grp_ProxGS_fu_305_coe_a_M_imag_address0, "grp_ProxGS_fu_305_coe_a_M_imag_address0");
    sc_trace(mVcdFile, grp_ProxGS_fu_305_coe_a_M_imag_ce0, "grp_ProxGS_fu_305_coe_a_M_imag_ce0");
    sc_trace(mVcdFile, grp_ProxGS_fu_305_coe_b_address0, "grp_ProxGS_fu_305_coe_b_address0");
    sc_trace(mVcdFile, grp_ProxGS_fu_305_coe_b_ce0, "grp_ProxGS_fu_305_coe_b_ce0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_ap_start, "grp_my_filter_v1_fu_316_ap_start");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_ap_done, "grp_my_filter_v1_fu_316_ap_done");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_ap_idle, "grp_my_filter_v1_fu_316_ap_idle");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_ap_ready, "grp_my_filter_v1_fu_316_ap_ready");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_f_V_address0, "grp_my_filter_v1_fu_316_f_V_address0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_f_V_ce0, "grp_my_filter_v1_fu_316_f_V_ce0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_f_V_address1, "grp_my_filter_v1_fu_316_f_V_address1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_f_V_ce1, "grp_my_filter_v1_fu_316_f_V_ce1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_adjChImg_V_address0, "grp_my_filter_v1_fu_316_adjChImg_V_address0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_adjChImg_V_ce0, "grp_my_filter_v1_fu_316_adjChImg_V_ce0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_adjChImg_V_address1, "grp_my_filter_v1_fu_316_adjChImg_V_address1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_adjChImg_V_ce1, "grp_my_filter_v1_fu_316_adjChImg_V_ce1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g1_V_address0, "grp_my_filter_v1_fu_316_g1_V_address0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g1_V_ce0, "grp_my_filter_v1_fu_316_g1_V_ce0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g1_V_address1, "grp_my_filter_v1_fu_316_g1_V_address1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g1_V_ce1, "grp_my_filter_v1_fu_316_g1_V_ce1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g1_V_we1, "grp_my_filter_v1_fu_316_g1_V_we1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g1_V_d1, "grp_my_filter_v1_fu_316_g1_V_d1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g2_V_address0, "grp_my_filter_v1_fu_316_g2_V_address0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g2_V_ce0, "grp_my_filter_v1_fu_316_g2_V_ce0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g2_V_address1, "grp_my_filter_v1_fu_316_g2_V_address1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g2_V_ce1, "grp_my_filter_v1_fu_316_g2_V_ce1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g2_V_we1, "grp_my_filter_v1_fu_316_g2_V_we1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g2_V_d1, "grp_my_filter_v1_fu_316_g2_V_d1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g3_V_address0, "grp_my_filter_v1_fu_316_g3_V_address0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g3_V_ce0, "grp_my_filter_v1_fu_316_g3_V_ce0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g3_V_address1, "grp_my_filter_v1_fu_316_g3_V_address1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g3_V_ce1, "grp_my_filter_v1_fu_316_g3_V_ce1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g3_V_we1, "grp_my_filter_v1_fu_316_g3_V_we1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g3_V_d1, "grp_my_filter_v1_fu_316_g3_V_d1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g4_V_address0, "grp_my_filter_v1_fu_316_g4_V_address0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g4_V_ce0, "grp_my_filter_v1_fu_316_g4_V_ce0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g4_V_address1, "grp_my_filter_v1_fu_316_g4_V_address1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g4_V_ce1, "grp_my_filter_v1_fu_316_g4_V_ce1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g4_V_we1, "grp_my_filter_v1_fu_316_g4_V_we1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g4_V_d1, "grp_my_filter_v1_fu_316_g4_V_d1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g5_V_address0, "grp_my_filter_v1_fu_316_g5_V_address0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g5_V_ce0, "grp_my_filter_v1_fu_316_g5_V_ce0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g5_V_address1, "grp_my_filter_v1_fu_316_g5_V_address1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g5_V_ce1, "grp_my_filter_v1_fu_316_g5_V_ce1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g5_V_we1, "grp_my_filter_v1_fu_316_g5_V_we1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g5_V_d1, "grp_my_filter_v1_fu_316_g5_V_d1");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g6_V_address0, "grp_my_filter_v1_fu_316_g6_V_address0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g6_V_ce0, "grp_my_filter_v1_fu_316_g6_V_ce0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g7_V_address0, "grp_my_filter_v1_fu_316_g7_V_address0");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_g7_V_ce0, "grp_my_filter_v1_fu_316_g7_V_ce0");
    sc_trace(mVcdFile, grp_array_copy_fu_330_ap_start, "grp_array_copy_fu_330_ap_start");
    sc_trace(mVcdFile, grp_array_copy_fu_330_ap_done, "grp_array_copy_fu_330_ap_done");
    sc_trace(mVcdFile, grp_array_copy_fu_330_ap_idle, "grp_array_copy_fu_330_ap_idle");
    sc_trace(mVcdFile, grp_array_copy_fu_330_ap_ready, "grp_array_copy_fu_330_ap_ready");
    sc_trace(mVcdFile, grp_array_copy_fu_330_data_in_V_address0, "grp_array_copy_fu_330_data_in_V_address0");
    sc_trace(mVcdFile, grp_array_copy_fu_330_data_in_V_ce0, "grp_array_copy_fu_330_data_in_V_ce0");
    sc_trace(mVcdFile, grp_array_copy_fu_330_data_in_V_q0, "grp_array_copy_fu_330_data_in_V_q0");
    sc_trace(mVcdFile, grp_array_copy_fu_330_data_out_V_address0, "grp_array_copy_fu_330_data_out_V_address0");
    sc_trace(mVcdFile, grp_array_copy_fu_330_data_out_V_ce0, "grp_array_copy_fu_330_data_out_V_ce0");
    sc_trace(mVcdFile, grp_array_copy_fu_330_data_out_V_we0, "grp_array_copy_fu_330_data_out_V_we0");
    sc_trace(mVcdFile, grp_array_copy_fu_330_data_out_V_d0, "grp_array_copy_fu_330_data_out_V_d0");
    sc_trace(mVcdFile, indvar_flatten_reg_239, "indvar_flatten_reg_239");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, y_0_i_reg_250, "y_0_i_reg_250");
    sc_trace(mVcdFile, x_0_i_reg_261, "x_0_i_reg_261");
    sc_trace(mVcdFile, ap_phi_mux_j_0_i_phi_fu_287_p4, "ap_phi_mux_j_0_i_phi_fu_287_p4");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, grp_ProxGS_fu_305_ap_start_reg, "grp_ProxGS_fu_305_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_my_filter_v1_fu_316_ap_start_reg, "grp_my_filter_v1_fu_316_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, grp_array_copy_fu_330_ap_start_reg, "grp_array_copy_fu_330_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, zext_ln321_3_fu_401_p1, "zext_ln321_3_fu_401_p1");
    sc_trace(mVcdFile, sub_ln214_fu_492_p2, "sub_ln214_fu_492_p2");
    sc_trace(mVcdFile, icmp_ln43_fu_357_p2, "icmp_ln43_fu_357_p2");
    sc_trace(mVcdFile, y_fu_351_p2, "y_fu_351_p2");
    sc_trace(mVcdFile, tmp_fu_379_p3, "tmp_fu_379_p3");
    sc_trace(mVcdFile, select_ln46_fu_363_p3, "select_ln46_fu_363_p3");
    sc_trace(mVcdFile, zext_ln321_fu_391_p1, "zext_ln321_fu_391_p1");
    sc_trace(mVcdFile, zext_ln44_fu_387_p1, "zext_ln44_fu_387_p1");
    sc_trace(mVcdFile, add_ln321_fu_395_p2, "add_ln321_fu_395_p2");
    sc_trace(mVcdFile, icmp_ln215_fu_436_p2, "icmp_ln215_fu_436_p2");
    sc_trace(mVcdFile, j_fu_430_p2, "j_fu_430_p2");
    sc_trace(mVcdFile, tmp_6_fu_458_p3, "tmp_6_fu_458_p3");
    sc_trace(mVcdFile, select_ln218_fu_442_p3, "select_ln218_fu_442_p3");
    sc_trace(mVcdFile, zext_ln321_4_fu_470_p1, "zext_ln321_4_fu_470_p1");
    sc_trace(mVcdFile, zext_ln216_fu_466_p1, "zext_ln216_fu_466_p1");
    sc_trace(mVcdFile, add_ln321_1_fu_474_p2, "add_ln321_1_fu_474_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_state7_on_subcall_done, "ap_block_state7_on_subcall_done");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
#endif

    }
    mHdltvinHandle.open("cross_channel_deblur.hdltvin.dat");
    mHdltvoutHandle.open("cross_channel_deblur.hdltvout.dat");
}

cross_channel_deblur::~cross_channel_deblur() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete x_bar_V_U;
    delete x_old_V_U;
    delete x_V_U;
    delete y_1_V_U;
    delete y_2_V_U;
    delete y_3_V_U;
    delete y_4_V_U;
    delete y_5_V_U;
    delete y_6_V_U;
    delete y_7_V_U;
    delete grp_ProxGS_fu_305;
    delete grp_my_filter_v1_fu_316;
    delete grp_array_copy_fu_330;
}

void cross_channel_deblur::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv1_0;
}

void cross_channel_deblur::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv8_0;
}

void cross_channel_deblur::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state10.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                    esl_seteq<1,1,1>(grp_ProxGS_fu_305_ap_done.read(), ap_const_logic_1))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state10.read()))) {
            ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state10.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                    esl_seteq<1,1,1>(grp_ProxGS_fu_305_ap_done.read(), ap_const_logic_1))) {
            ap_enable_reg_pp1_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_ProxGS_fu_305_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
            grp_ProxGS_fu_305_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_ProxGS_fu_305_ap_ready.read())) {
            grp_ProxGS_fu_305_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_array_copy_fu_330_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
              esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
            grp_array_copy_fu_330_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_array_copy_fu_330_ap_ready.read())) {
            grp_array_copy_fu_330_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_my_filter_v1_fu_316_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            grp_my_filter_v1_fu_316_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_my_filter_v1_fu_316_ap_ready.read())) {
            grp_my_filter_v1_fu_316_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln213_fu_418_p2.read()))) {
        i_0_i_reg_294 = i_fu_486_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(grp_ProxGS_fu_305_ap_done.read(), ap_const_logic_1))) {
        i_0_i_reg_294 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln213_fu_418_p2.read()))) {
        indvar_flatten11_reg_272 = add_ln213_fu_424_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(grp_ProxGS_fu_305_ap_done.read(), ap_const_logic_1))) {
        indvar_flatten11_reg_272 = ap_const_lv15_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_fu_339_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_239 = add_ln41_fu_345_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(grp_array_copy_fu_330_ap_done.read(), ap_const_logic_1))) {
        indvar_flatten_reg_239 = ap_const_lv15_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln213_reg_517.read()))) {
        j_0_i_reg_283 = select_ln218_1_reg_526.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(grp_ProxGS_fu_305_ap_done.read(), ap_const_logic_1))) {
        j_0_i_reg_283 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_fu_339_p2.read(), ap_const_lv1_0))) {
        x_0_i_reg_261 = x_fu_412_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(grp_array_copy_fu_330_ap_done.read(), ap_const_logic_1))) {
        x_0_i_reg_261 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_fu_339_p2.read(), ap_const_lv1_0))) {
        y_0_i_reg_250 = select_ln46_1_fu_371_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(grp_array_copy_fu_330_ap_done.read(), ap_const_logic_1))) {
        y_0_i_reg_250 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln213_reg_517 = icmp_ln213_fu_418_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln213_fu_418_p2.read()))) {
        select_ln218_1_reg_526 = select_ln218_1_fu_450_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln213_fu_418_p2.read()))) {
        zext_ln321_5_reg_531 = zext_ln321_5_fu_480_p1.read();
    }
}

void cross_channel_deblur::thread_Img_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        Img_V_address0 = grp_array_copy_fu_330_data_out_V_address0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        Img_V_address0 = grp_array_copy_fu_330_data_in_V_address0.read();
    } else {
        Img_V_address0 = "XXXXXXXXXXXXXX";
    }
}

void cross_channel_deblur::thread_Img_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        Img_V_ce0 = grp_array_copy_fu_330_data_out_V_ce0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        Img_V_ce0 = grp_array_copy_fu_330_data_in_V_ce0.read();
    } else {
        Img_V_ce0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_Img_V_d0() {
    Img_V_d0 = grp_array_copy_fu_330_data_out_V_d0.read();
}

void cross_channel_deblur::thread_Img_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        Img_V_we0 = grp_array_copy_fu_330_data_out_V_we0.read();
    } else {
        Img_V_we0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_add_ln213_fu_424_p2() {
    add_ln213_fu_424_p2 = (!indvar_flatten11_reg_272.read().is_01() || !ap_const_lv15_1.is_01())? sc_lv<15>(): (sc_biguint<15>(indvar_flatten11_reg_272.read()) + sc_biguint<15>(ap_const_lv15_1));
}

void cross_channel_deblur::thread_add_ln321_1_fu_474_p2() {
    add_ln321_1_fu_474_p2 = (!zext_ln321_4_fu_470_p1.read().is_01() || !zext_ln216_fu_466_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln321_4_fu_470_p1.read()) + sc_biguint<16>(zext_ln216_fu_466_p1.read()));
}

void cross_channel_deblur::thread_add_ln321_fu_395_p2() {
    add_ln321_fu_395_p2 = (!zext_ln321_fu_391_p1.read().is_01() || !zext_ln44_fu_387_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln321_fu_391_p1.read()) + sc_biguint<16>(zext_ln44_fu_387_p1.read()));
}

void cross_channel_deblur::thread_add_ln41_fu_345_p2() {
    add_ln41_fu_345_p2 = (!indvar_flatten_reg_239.read().is_01() || !ap_const_lv15_1.is_01())? sc_lv<15>(): (sc_biguint<15>(indvar_flatten_reg_239.read()) + sc_biguint<15>(ap_const_lv15_1));
}

void cross_channel_deblur::thread_adjChImg_V_address0() {
    adjChImg_V_address0 = grp_my_filter_v1_fu_316_adjChImg_V_address0.read();
}

void cross_channel_deblur::thread_adjChImg_V_address1() {
    adjChImg_V_address1 = grp_my_filter_v1_fu_316_adjChImg_V_address1.read();
}

void cross_channel_deblur::thread_adjChImg_V_ce0() {
    adjChImg_V_ce0 = grp_my_filter_v1_fu_316_adjChImg_V_ce0.read();
}

void cross_channel_deblur::thread_adjChImg_V_ce1() {
    adjChImg_V_ce1 = grp_my_filter_v1_fu_316_adjChImg_V_ce1.read();
}

void cross_channel_deblur::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[9];
}

void cross_channel_deblur::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void cross_channel_deblur::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[10];
}

void cross_channel_deblur::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[11];
}

void cross_channel_deblur::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void cross_channel_deblur::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void cross_channel_deblur::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void cross_channel_deblur::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void cross_channel_deblur::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void cross_channel_deblur::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void cross_channel_deblur::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void cross_channel_deblur::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void cross_channel_deblur::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void cross_channel_deblur::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void cross_channel_deblur::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void cross_channel_deblur::thread_ap_block_state10_pp1_stage0_iter0() {
    ap_block_state10_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void cross_channel_deblur::thread_ap_block_state11_pp1_stage0_iter1() {
    ap_block_state11_pp1_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void cross_channel_deblur::thread_ap_block_state7_on_subcall_done() {
    ap_block_state7_on_subcall_done = (esl_seteq<1,1,1>(ap_const_logic_0, grp_array_copy_fu_330_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_my_filter_v1_fu_316_ap_done.read()));
}

void cross_channel_deblur::thread_ap_condition_pp1_exit_iter0_state10() {
    if (esl_seteq<1,1,1>(icmp_ln213_fu_418_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp1_exit_iter0_state10 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state10 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_ap_done() {
    if ((esl_seteq<1,1,1>(grp_array_copy_fu_330_ap_done.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void cross_channel_deblur::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_ap_phi_mux_j_0_i_phi_fu_287_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln213_reg_517.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_j_0_i_phi_fu_287_p4 = select_ln218_1_reg_526.read();
    } else {
        ap_phi_mux_j_0_i_phi_fu_287_p4 = j_0_i_reg_283.read();
    }
}

void cross_channel_deblur::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(grp_array_copy_fu_330_ap_done.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_coe_a_M_imag_address0() {
    coe_a_M_imag_address0 = grp_ProxGS_fu_305_coe_a_M_imag_address0.read();
}

void cross_channel_deblur::thread_coe_a_M_imag_ce0() {
    coe_a_M_imag_ce0 = grp_ProxGS_fu_305_coe_a_M_imag_ce0.read();
}

void cross_channel_deblur::thread_coe_a_M_real_address0() {
    coe_a_M_real_address0 = grp_ProxGS_fu_305_coe_a_M_real_address0.read();
}

void cross_channel_deblur::thread_coe_a_M_real_ce0() {
    coe_a_M_real_ce0 = grp_ProxGS_fu_305_coe_a_M_real_ce0.read();
}

void cross_channel_deblur::thread_coe_b_address0() {
    coe_b_address0 = grp_ProxGS_fu_305_coe_b_address0.read();
}

void cross_channel_deblur::thread_coe_b_ce0() {
    coe_b_ce0 = grp_ProxGS_fu_305_coe_b_ce0.read();
}

void cross_channel_deblur::thread_grp_ProxGS_fu_305_ap_start() {
    grp_ProxGS_fu_305_ap_start = grp_ProxGS_fu_305_ap_start_reg.read();
}

void cross_channel_deblur::thread_grp_array_copy_fu_330_ap_start() {
    grp_array_copy_fu_330_ap_start = grp_array_copy_fu_330_ap_start_reg.read();
}

void cross_channel_deblur::thread_grp_array_copy_fu_330_data_in_V_q0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        grp_array_copy_fu_330_data_in_V_q0 = x_V_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        grp_array_copy_fu_330_data_in_V_q0 = Img_V_q0.read();
    } else {
        grp_array_copy_fu_330_data_in_V_q0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void cross_channel_deblur::thread_grp_my_filter_v1_fu_316_ap_start() {
    grp_my_filter_v1_fu_316_ap_start = grp_my_filter_v1_fu_316_ap_start_reg.read();
}

void cross_channel_deblur::thread_i_fu_486_p2() {
    i_fu_486_p2 = (!select_ln218_fu_442_p3.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(select_ln218_fu_442_p3.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void cross_channel_deblur::thread_icmp_ln213_fu_418_p2() {
    icmp_ln213_fu_418_p2 = (!indvar_flatten11_reg_272.read().is_01() || !ap_const_lv15_4000.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten11_reg_272.read() == ap_const_lv15_4000);
}

void cross_channel_deblur::thread_icmp_ln215_fu_436_p2() {
    icmp_ln215_fu_436_p2 = (!i_0_i_reg_294.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_reg_294.read() == ap_const_lv8_80);
}

void cross_channel_deblur::thread_icmp_ln41_fu_339_p2() {
    icmp_ln41_fu_339_p2 = (!indvar_flatten_reg_239.read().is_01() || !ap_const_lv15_4000.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_239.read() == ap_const_lv15_4000);
}

void cross_channel_deblur::thread_icmp_ln43_fu_357_p2() {
    icmp_ln43_fu_357_p2 = (!x_0_i_reg_261.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(x_0_i_reg_261.read() == ap_const_lv8_80);
}

void cross_channel_deblur::thread_j_fu_430_p2() {
    j_fu_430_p2 = (!ap_phi_mux_j_0_i_phi_fu_287_p4.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(ap_phi_mux_j_0_i_phi_fu_287_p4.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void cross_channel_deblur::thread_select_ln218_1_fu_450_p3() {
    select_ln218_1_fu_450_p3 = (!icmp_ln215_fu_436_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln215_fu_436_p2.read()[0].to_bool())? j_fu_430_p2.read(): ap_phi_mux_j_0_i_phi_fu_287_p4.read());
}

void cross_channel_deblur::thread_select_ln218_fu_442_p3() {
    select_ln218_fu_442_p3 = (!icmp_ln215_fu_436_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln215_fu_436_p2.read()[0].to_bool())? ap_const_lv8_0: i_0_i_reg_294.read());
}

void cross_channel_deblur::thread_select_ln46_1_fu_371_p3() {
    select_ln46_1_fu_371_p3 = (!icmp_ln43_fu_357_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln43_fu_357_p2.read()[0].to_bool())? y_fu_351_p2.read(): y_0_i_reg_250.read());
}

void cross_channel_deblur::thread_select_ln46_fu_363_p3() {
    select_ln46_fu_363_p3 = (!icmp_ln43_fu_357_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln43_fu_357_p2.read()[0].to_bool())? ap_const_lv8_0: x_0_i_reg_261.read());
}

void cross_channel_deblur::thread_sub_ln214_fu_492_p2() {
    sub_ln214_fu_492_p2 = (!x_V_q0.read().is_01() || !x_old_V_q0.read().is_01())? sc_lv<8>(): (sc_biguint<8>(x_V_q0.read()) - sc_biguint<8>(x_old_V_q0.read()));
}

void cross_channel_deblur::thread_tmp_6_fu_458_p3() {
    tmp_6_fu_458_p3 = esl_concat<8,7>(select_ln218_1_fu_450_p3.read(), ap_const_lv7_0);
}

void cross_channel_deblur::thread_tmp_fu_379_p3() {
    tmp_fu_379_p3 = esl_concat<8,7>(select_ln46_1_fu_371_p3.read(), ap_const_lv7_0);
}

void cross_channel_deblur::thread_x_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        x_V_address0 =  (sc_lv<14>) (zext_ln321_5_fu_480_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x_V_address0 = grp_array_copy_fu_330_data_out_V_address0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        x_V_address0 = grp_array_copy_fu_330_data_in_V_address0.read();
    } else {
        x_V_address0 = "XXXXXXXXXXXXXX";
    }
}

void cross_channel_deblur::thread_x_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        x_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x_V_ce0 = grp_array_copy_fu_330_data_out_V_ce0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        x_V_ce0 = grp_array_copy_fu_330_data_in_V_ce0.read();
    } else {
        x_V_ce0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_x_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x_V_we0 = grp_array_copy_fu_330_data_out_V_we0.read();
    } else {
        x_V_we0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_x_bar_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        x_bar_V_address0 =  (sc_lv<14>) (zext_ln321_5_reg_531.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        x_bar_V_address0 = grp_array_copy_fu_330_data_out_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        x_bar_V_address0 = grp_my_filter_v1_fu_316_f_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        x_bar_V_address0 = grp_ProxGS_fu_305_x_io_V_address0.read();
    } else {
        x_bar_V_address0 = "XXXXXXXXXXXXXX";
    }
}

void cross_channel_deblur::thread_x_bar_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()))) {
        x_bar_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        x_bar_V_ce0 = grp_array_copy_fu_330_data_out_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        x_bar_V_ce0 = grp_my_filter_v1_fu_316_f_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        x_bar_V_ce0 = grp_ProxGS_fu_305_x_io_V_ce0.read();
    } else {
        x_bar_V_ce0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_x_bar_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        x_bar_V_ce1 = grp_my_filter_v1_fu_316_f_V_ce1.read();
    } else {
        x_bar_V_ce1 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_x_bar_V_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        x_bar_V_d0 = sub_ln214_fu_492_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        x_bar_V_d0 = grp_array_copy_fu_330_data_out_V_d0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        x_bar_V_d0 = grp_ProxGS_fu_305_x_io_V_d0.read();
    } else {
        x_bar_V_d0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void cross_channel_deblur::thread_x_bar_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln213_reg_517.read()))) {
        x_bar_V_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        x_bar_V_we0 = grp_array_copy_fu_330_data_out_V_we0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        x_bar_V_we0 = grp_ProxGS_fu_305_x_io_V_we0.read();
    } else {
        x_bar_V_we0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_x_fu_412_p2() {
    x_fu_412_p2 = (!select_ln46_fu_363_p3.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(select_ln46_fu_363_p3.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void cross_channel_deblur::thread_x_old_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        x_old_V_address0 =  (sc_lv<14>) (zext_ln321_5_fu_480_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        x_old_V_address0 = grp_array_copy_fu_330_data_out_V_address0.read();
    } else {
        x_old_V_address0 = "XXXXXXXXXXXXXX";
    }
}

void cross_channel_deblur::thread_x_old_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        x_old_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        x_old_V_ce0 = grp_array_copy_fu_330_data_out_V_ce0.read();
    } else {
        x_old_V_ce0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_x_old_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        x_old_V_we0 = grp_array_copy_fu_330_data_out_V_we0.read();
    } else {
        x_old_V_we0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_1_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_1_V_address0 =  (sc_lv<14>) (zext_ln321_3_fu_401_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_1_V_address0 = grp_my_filter_v1_fu_316_g1_V_address0.read();
    } else {
        y_1_V_address0 = "XXXXXXXXXXXXXX";
    }
}

void cross_channel_deblur::thread_y_1_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_1_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_1_V_ce0 = grp_my_filter_v1_fu_316_g1_V_ce0.read();
    } else {
        y_1_V_ce0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_1_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_1_V_ce1 = grp_my_filter_v1_fu_316_g1_V_ce1.read();
    } else {
        y_1_V_ce1 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_1_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_fu_339_p2.read(), ap_const_lv1_0))) {
        y_1_V_we0 = ap_const_logic_1;
    } else {
        y_1_V_we0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_1_V_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_1_V_we1 = grp_my_filter_v1_fu_316_g1_V_we1.read();
    } else {
        y_1_V_we1 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_2_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_2_V_address0 =  (sc_lv<14>) (zext_ln321_3_fu_401_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_2_V_address0 = grp_my_filter_v1_fu_316_g2_V_address0.read();
    } else {
        y_2_V_address0 = "XXXXXXXXXXXXXX";
    }
}

void cross_channel_deblur::thread_y_2_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_2_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_2_V_ce0 = grp_my_filter_v1_fu_316_g2_V_ce0.read();
    } else {
        y_2_V_ce0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_2_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_2_V_ce1 = grp_my_filter_v1_fu_316_g2_V_ce1.read();
    } else {
        y_2_V_ce1 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_2_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_fu_339_p2.read(), ap_const_lv1_0))) {
        y_2_V_we0 = ap_const_logic_1;
    } else {
        y_2_V_we0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_2_V_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_2_V_we1 = grp_my_filter_v1_fu_316_g2_V_we1.read();
    } else {
        y_2_V_we1 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_3_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_3_V_address0 =  (sc_lv<14>) (zext_ln321_3_fu_401_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_3_V_address0 = grp_my_filter_v1_fu_316_g3_V_address0.read();
    } else {
        y_3_V_address0 = "XXXXXXXXXXXXXX";
    }
}

void cross_channel_deblur::thread_y_3_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_3_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_3_V_ce0 = grp_my_filter_v1_fu_316_g3_V_ce0.read();
    } else {
        y_3_V_ce0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_3_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_3_V_ce1 = grp_my_filter_v1_fu_316_g3_V_ce1.read();
    } else {
        y_3_V_ce1 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_3_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_fu_339_p2.read(), ap_const_lv1_0))) {
        y_3_V_we0 = ap_const_logic_1;
    } else {
        y_3_V_we0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_3_V_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_3_V_we1 = grp_my_filter_v1_fu_316_g3_V_we1.read();
    } else {
        y_3_V_we1 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_4_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_4_V_address0 =  (sc_lv<14>) (zext_ln321_3_fu_401_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_4_V_address0 = grp_my_filter_v1_fu_316_g4_V_address0.read();
    } else {
        y_4_V_address0 = "XXXXXXXXXXXXXX";
    }
}

void cross_channel_deblur::thread_y_4_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_4_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_4_V_ce0 = grp_my_filter_v1_fu_316_g4_V_ce0.read();
    } else {
        y_4_V_ce0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_4_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_4_V_ce1 = grp_my_filter_v1_fu_316_g4_V_ce1.read();
    } else {
        y_4_V_ce1 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_4_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_fu_339_p2.read(), ap_const_lv1_0))) {
        y_4_V_we0 = ap_const_logic_1;
    } else {
        y_4_V_we0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_4_V_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_4_V_we1 = grp_my_filter_v1_fu_316_g4_V_we1.read();
    } else {
        y_4_V_we1 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_5_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_5_V_address0 =  (sc_lv<14>) (zext_ln321_3_fu_401_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_5_V_address0 = grp_my_filter_v1_fu_316_g5_V_address0.read();
    } else {
        y_5_V_address0 = "XXXXXXXXXXXXXX";
    }
}

void cross_channel_deblur::thread_y_5_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_5_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_5_V_ce0 = grp_my_filter_v1_fu_316_g5_V_ce0.read();
    } else {
        y_5_V_ce0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_5_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_5_V_ce1 = grp_my_filter_v1_fu_316_g5_V_ce1.read();
    } else {
        y_5_V_ce1 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_5_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_fu_339_p2.read(), ap_const_lv1_0))) {
        y_5_V_we0 = ap_const_logic_1;
    } else {
        y_5_V_we0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_5_V_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_5_V_we1 = grp_my_filter_v1_fu_316_g5_V_we1.read();
    } else {
        y_5_V_we1 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_6_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_6_V_address0 =  (sc_lv<14>) (zext_ln321_3_fu_401_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_6_V_address0 = grp_my_filter_v1_fu_316_g6_V_address0.read();
    } else {
        y_6_V_address0 = "XXXXXXXXXXXXXX";
    }
}

void cross_channel_deblur::thread_y_6_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_6_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_6_V_ce0 = grp_my_filter_v1_fu_316_g6_V_ce0.read();
    } else {
        y_6_V_ce0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_6_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_fu_339_p2.read(), ap_const_lv1_0))) {
        y_6_V_we0 = ap_const_logic_1;
    } else {
        y_6_V_we0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_7_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_7_V_address0 =  (sc_lv<14>) (zext_ln321_3_fu_401_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_7_V_address0 = grp_my_filter_v1_fu_316_g7_V_address0.read();
    } else {
        y_7_V_address0 = "XXXXXXXXXXXXXX";
    }
}

void cross_channel_deblur::thread_y_7_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_7_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_7_V_ce0 = grp_my_filter_v1_fu_316_g7_V_ce0.read();
    } else {
        y_7_V_ce0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_7_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_fu_339_p2.read(), ap_const_lv1_0))) {
        y_7_V_we0 = ap_const_logic_1;
    } else {
        y_7_V_we0 = ap_const_logic_0;
    }
}

void cross_channel_deblur::thread_y_fu_351_p2() {
    y_fu_351_p2 = (!y_0_i_reg_250.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(y_0_i_reg_250.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void cross_channel_deblur::thread_zext_ln216_fu_466_p1() {
    zext_ln216_fu_466_p1 = esl_zext<16,15>(tmp_6_fu_458_p3.read());
}

void cross_channel_deblur::thread_zext_ln321_3_fu_401_p1() {
    zext_ln321_3_fu_401_p1 = esl_zext<64,16>(add_ln321_fu_395_p2.read());
}

void cross_channel_deblur::thread_zext_ln321_4_fu_470_p1() {
    zext_ln321_4_fu_470_p1 = esl_zext<16,8>(select_ln218_fu_442_p3.read());
}

void cross_channel_deblur::thread_zext_ln321_5_fu_480_p1() {
    zext_ln321_5_fu_480_p1 = esl_zext<64,16>(add_ln321_1_fu_474_p2.read());
}

void cross_channel_deblur::thread_zext_ln321_fu_391_p1() {
    zext_ln321_fu_391_p1 = esl_zext<16,8>(select_ln46_fu_363_p3.read());
}

void cross_channel_deblur::thread_zext_ln44_fu_387_p1() {
    zext_ln44_fu_387_p1 = esl_zext<16,15>(tmp_fu_379_p3.read());
}

void cross_channel_deblur::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(grp_array_copy_fu_330_ap_done.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(grp_array_copy_fu_330_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln41_fu_339_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_block_state7_on_subcall_done.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(grp_ProxGS_fu_305_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 512 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln213_fu_418_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln213_fu_418_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(grp_array_copy_fu_330_ap_done.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<12>) ("XXXXXXXXXXXX");
            break;
    }
}

void cross_channel_deblur::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Img_V_address0\" :  \"" << Img_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Img_V_ce0\" :  \"" << Img_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Img_V_we0\" :  \"" << Img_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Img_V_d0\" :  \"" << Img_V_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Img_V_q0\" :  \"" << Img_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"adjChImg_V_address0\" :  \"" << adjChImg_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"adjChImg_V_ce0\" :  \"" << adjChImg_V_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"adjChImg_V_q0\" :  \"" << adjChImg_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"adjChImg_V_address1\" :  \"" << adjChImg_V_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"adjChImg_V_ce1\" :  \"" << adjChImg_V_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"adjChImg_V_q1\" :  \"" << adjChImg_V_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"coe_a_M_real_address0\" :  \"" << coe_a_M_real_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"coe_a_M_real_ce0\" :  \"" << coe_a_M_real_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"coe_a_M_real_q0\" :  \"" << coe_a_M_real_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"coe_a_M_imag_address0\" :  \"" << coe_a_M_imag_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"coe_a_M_imag_ce0\" :  \"" << coe_a_M_imag_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"coe_a_M_imag_q0\" :  \"" << coe_a_M_imag_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"coe_b_address0\" :  \"" << coe_b_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"coe_b_ce0\" :  \"" << coe_b_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"coe_b_q0\" :  \"" << coe_b_q0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

