// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fft_top_2D.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fft_top_2D::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fft_top_2D::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<15> fft_top_2D::ap_ST_fsm_state1 = "1";
const sc_lv<15> fft_top_2D::ap_ST_fsm_state2 = "10";
const sc_lv<15> fft_top_2D::ap_ST_fsm_state3 = "100";
const sc_lv<15> fft_top_2D::ap_ST_fsm_state4 = "1000";
const sc_lv<15> fft_top_2D::ap_ST_fsm_state5 = "10000";
const sc_lv<15> fft_top_2D::ap_ST_fsm_state6 = "100000";
const sc_lv<15> fft_top_2D::ap_ST_fsm_state7 = "1000000";
const sc_lv<15> fft_top_2D::ap_ST_fsm_state8 = "10000000";
const sc_lv<15> fft_top_2D::ap_ST_fsm_state9 = "100000000";
const sc_lv<15> fft_top_2D::ap_ST_fsm_state10 = "1000000000";
const sc_lv<15> fft_top_2D::ap_ST_fsm_state11 = "10000000000";
const sc_lv<15> fft_top_2D::ap_ST_fsm_state12 = "100000000000";
const sc_lv<15> fft_top_2D::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<15> fft_top_2D::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<15> fft_top_2D::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<32> fft_top_2D::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> fft_top_2D::ap_const_lv32_1 = "1";
const sc_lv<32> fft_top_2D::ap_const_lv32_2 = "10";
const sc_lv<32> fft_top_2D::ap_const_lv32_3 = "11";
const sc_lv<1> fft_top_2D::ap_const_lv1_0 = "0";
const sc_lv<32> fft_top_2D::ap_const_lv32_4 = "100";
const sc_lv<32> fft_top_2D::ap_const_lv32_7 = "111";
const sc_lv<32> fft_top_2D::ap_const_lv32_9 = "1001";
const sc_lv<32> fft_top_2D::ap_const_lv32_A = "1010";
const sc_lv<32> fft_top_2D::ap_const_lv32_D = "1101";
const sc_lv<7> fft_top_2D::ap_const_lv7_0 = "0000000";
const sc_lv<1> fft_top_2D::ap_const_lv1_1 = "1";
const sc_lv<8> fft_top_2D::ap_const_lv8_0 = "00000000";
const sc_lv<32> fft_top_2D::ap_const_lv32_5 = "101";
const sc_lv<32> fft_top_2D::ap_const_lv32_6 = "110";
const bool fft_top_2D::ap_const_boolean_0 = false;
const sc_lv<32> fft_top_2D::ap_const_lv32_8 = "1000";
const sc_lv<32> fft_top_2D::ap_const_lv32_B = "1011";
const sc_lv<32> fft_top_2D::ap_const_lv32_C = "1100";
const sc_lv<32> fft_top_2D::ap_const_lv32_E = "1110";
const sc_lv<64> fft_top_2D::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> fft_top_2D::ap_const_lv32_20 = "100000";
const sc_lv<32> fft_top_2D::ap_const_lv32_3F = "111111";
const sc_lv<7> fft_top_2D::ap_const_lv7_1 = "1";
const sc_lv<7> fft_top_2D::ap_const_lv7_7F = "1111111";
const sc_lv<8> fft_top_2D::ap_const_lv8_80 = "10000000";
const sc_lv<8> fft_top_2D::ap_const_lv8_1 = "1";
const bool fft_top_2D::ap_const_boolean_1 = true;

fft_top_2D::fft_top_2D(sc_module_name name) : sc_module(name), mVcdFile(0) {
    buffer_out_U = new fft_top_2D_bufferhbi("buffer_out_U");
    buffer_out_U->clk(ap_clk);
    buffer_out_U->reset(ap_rst);
    buffer_out_U->address0(buffer_out_address0);
    buffer_out_U->ce0(buffer_out_ce0);
    buffer_out_U->we0(buffer_out_we0);
    buffer_out_U->d0(buffer_out_d0);
    buffer_out_U->q0(buffer_out_q0);
    buffer_in_U = new fft_top_2D_bufferhbi("buffer_in_U");
    buffer_in_U->clk(ap_clk);
    buffer_in_U->reset(ap_rst);
    buffer_in_U->address0(buffer_in_address0);
    buffer_in_U->ce0(buffer_in_ce0);
    buffer_in_U->we0(buffer_in_we0);
    buffer_in_U->d0(buffer_in_d0);
    buffer_in_U->q0(buffer_in_q0);
    grp_fft_top_fu_310 = new fft_top("grp_fft_top_fu_310");
    grp_fft_top_fu_310->direction(direction);
    grp_fft_top_fu_310->in_r_address0(grp_fft_top_fu_310_in_r_address0);
    grp_fft_top_fu_310->in_r_ce0(grp_fft_top_fu_310_in_r_ce0);
    grp_fft_top_fu_310->in_r_d0(grp_fft_top_fu_310_in_r_d0);
    grp_fft_top_fu_310->in_r_q0(buffer_in_q0);
    grp_fft_top_fu_310->in_r_we0(grp_fft_top_fu_310_in_r_we0);
    grp_fft_top_fu_310->in_r_address1(grp_fft_top_fu_310_in_r_address1);
    grp_fft_top_fu_310->in_r_ce1(grp_fft_top_fu_310_in_r_ce1);
    grp_fft_top_fu_310->in_r_d1(grp_fft_top_fu_310_in_r_d1);
    grp_fft_top_fu_310->in_r_q1(ap_var_for_const0);
    grp_fft_top_fu_310->in_r_we1(grp_fft_top_fu_310_in_r_we1);
    grp_fft_top_fu_310->out_r_address0(grp_fft_top_fu_310_out_r_address0);
    grp_fft_top_fu_310->out_r_ce0(grp_fft_top_fu_310_out_r_ce0);
    grp_fft_top_fu_310->out_r_d0(grp_fft_top_fu_310_out_r_d0);
    grp_fft_top_fu_310->out_r_q0(ap_var_for_const0);
    grp_fft_top_fu_310->out_r_we0(grp_fft_top_fu_310_out_r_we0);
    grp_fft_top_fu_310->out_r_address1(grp_fft_top_fu_310_out_r_address1);
    grp_fft_top_fu_310->out_r_ce1(grp_fft_top_fu_310_out_r_ce1);
    grp_fft_top_fu_310->out_r_d1(grp_fft_top_fu_310_out_r_d1);
    grp_fft_top_fu_310->out_r_q1(ap_var_for_const0);
    grp_fft_top_fu_310->out_r_we1(grp_fft_top_fu_310_out_r_we1);
    grp_fft_top_fu_310->ovflo(grp_fft_top_fu_310_ovflo);
    grp_fft_top_fu_310->ap_clk(ap_clk);
    grp_fft_top_fu_310->ap_rst(ap_rst);
    grp_fft_top_fu_310->direction_ap_vld(ap_var_for_const1);
    grp_fft_top_fu_310->direction_ap_ack(grp_fft_top_fu_310_direction_ap_ack);
    grp_fft_top_fu_310->ap_start(grp_fft_top_fu_310_ap_start);
    grp_fft_top_fu_310->ovflo_ap_vld(grp_fft_top_fu_310_ovflo_ap_vld);
    grp_fft_top_fu_310->ap_done(grp_fft_top_fu_310_ap_done);
    grp_fft_top_fu_310->ap_ready(grp_fft_top_fu_310_ap_ready);
    grp_fft_top_fu_310->ap_idle(grp_fft_top_fu_310_ap_idle);
    grp_fft_top_fu_310->ap_continue(grp_fft_top_fu_310_ap_continue);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln199_1_fu_345_p2);
    sensitive << ( phi_ln199_1_reg_231 );

    SC_METHOD(thread_add_ln199_fu_328_p2);
    sensitive << ( phi_ln199_reg_220 );

    SC_METHOD(thread_add_ln204_fu_407_p2);
    sensitive << ( zext_ln203_reg_646 );
    sensitive << ( zext_ln204_1_fu_403_p1 );

    SC_METHOD(thread_add_ln210_fu_461_p2);
    sensitive << ( zext_ln203_reg_646 );
    sensitive << ( zext_ln210_1_fu_457_p1 );

    SC_METHOD(thread_add_ln218_fu_525_p2);
    sensitive << ( zext_ln217_reg_696 );
    sensitive << ( zext_ln218_1_fu_521_p1 );

    SC_METHOD(thread_add_ln223_fu_587_p2);
    sensitive << ( zext_ln217_reg_696 );
    sensitive << ( zext_ln223_1_fu_583_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state13_on_subcall_done);
    sensitive << ( ap_sync_grp_fft_top_fu_310_ap_ready );
    sensitive << ( ap_sync_grp_fft_top_fu_310_ap_done );

    SC_METHOD(thread_ap_block_state7_on_subcall_done);
    sensitive << ( ap_sync_grp_fft_top_fu_310_ap_ready );
    sensitive << ( ap_sync_grp_fft_top_fu_310_ap_done );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln216_fu_485_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln216_fu_485_p2 );

    SC_METHOD(thread_ap_sync_grp_fft_top_fu_310_ap_done);
    sensitive << ( grp_fft_top_fu_310_ap_done );
    sensitive << ( ap_sync_reg_grp_fft_top_fu_310_ap_done );

    SC_METHOD(thread_ap_sync_grp_fft_top_fu_310_ap_ready);
    sensitive << ( grp_fft_top_fu_310_ap_ready );
    sensitive << ( ap_sync_reg_grp_fft_top_fu_310_ap_ready );

    SC_METHOD(thread_bitcast_ln204_1_fu_427_p1);
    sensitive << ( in_M_imag_q0 );

    SC_METHOD(thread_bitcast_ln204_fu_423_p1);
    sensitive << ( in_M_real_q0 );

    SC_METHOD(thread_bitcast_ln210_1_fu_480_p1);
    sensitive << ( grp_fu_318_p4 );

    SC_METHOD(thread_bitcast_ln210_fu_475_p1);
    sensitive << ( trunc_ln210_fu_471_p1 );

    SC_METHOD(thread_bitcast_ln218_1_fu_545_p1);
    sensitive << ( in_M_imag_q0 );

    SC_METHOD(thread_bitcast_ln218_fu_541_p1);
    sensitive << ( in_M_real_q0 );

    SC_METHOD(thread_bitcast_ln223_1_fu_606_p1);
    sensitive << ( grp_fu_318_p4 );

    SC_METHOD(thread_bitcast_ln223_fu_601_p1);
    sensitive << ( trunc_ln223_fu_597_p1 );

    SC_METHOD(thread_buffer_in_M_imag_ad_1_fu_549_p3);
    sensitive << ( bitcast_ln218_1_fu_545_p1 );
    sensitive << ( bitcast_ln218_fu_541_p1 );

    SC_METHOD(thread_buffer_in_M_imag_ad_fu_431_p3);
    sensitive << ( bitcast_ln204_1_fu_427_p1 );
    sensitive << ( bitcast_ln204_fu_423_p1 );

    SC_METHOD(thread_buffer_in_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_fft_top_fu_310_in_r_address0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( zext_ln199_fu_334_p1 );
    sensitive << ( zext_ln204_fu_418_p1 );
    sensitive << ( zext_ln218_fu_536_p1 );

    SC_METHOD(thread_buffer_in_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_fft_top_fu_310_in_r_ce0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_buffer_in_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( buffer_in_M_imag_ad_fu_431_p3 );
    sensitive << ( buffer_in_M_imag_ad_1_fu_549_p3 );

    SC_METHOD(thread_buffer_in_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_buffer_out_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( grp_fft_top_fu_310_out_r_address0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( zext_ln199_1_fu_351_p1 );
    sensitive << ( zext_ln210_fu_452_p1 );
    sensitive << ( zext_ln223_fu_570_p1 );

    SC_METHOD(thread_buffer_out_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( grp_fft_top_fu_310_out_r_ce0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_buffer_out_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_fft_top_fu_310_out_r_d0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_buffer_out_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_fft_top_fu_310_out_r_we0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_grp_fft_top_fu_310_ap_continue);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_block_state7_on_subcall_done );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_block_state13_on_subcall_done );

    SC_METHOD(thread_grp_fft_top_fu_310_ap_start);
    sensitive << ( grp_fft_top_fu_310_ap_start_reg );

    SC_METHOD(thread_grp_fu_318_p4);
    sensitive << ( buffer_out_q0 );

    SC_METHOD(thread_i_1_fu_373_p2);
    sensitive << ( i_0_reg_242 );

    SC_METHOD(thread_i_2_fu_564_p2);
    sensitive << ( i4_0_reg_299 );

    SC_METHOD(thread_i_fu_507_p2);
    sensitive << ( i3_0_reg_287 );

    SC_METHOD(thread_icmp_ln199_1_fu_356_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( phi_ln199_1_reg_231 );

    SC_METHOD(thread_icmp_ln199_fu_339_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( phi_ln199_reg_220 );

    SC_METHOD(thread_icmp_ln202_fu_367_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i_0_reg_242 );

    SC_METHOD(thread_icmp_ln203_fu_391_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( j_0_reg_253 );

    SC_METHOD(thread_icmp_ln209_fu_440_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( k_0_reg_265 );

    SC_METHOD(thread_icmp_ln216_fu_485_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( j2_0_reg_276 );

    SC_METHOD(thread_icmp_ln217_fu_501_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( i3_0_reg_287 );

    SC_METHOD(thread_icmp_ln222_fu_558_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( i4_0_reg_299 );

    SC_METHOD(thread_in_M_imag_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( zext_ln204_2_fu_412_p1 );
    sensitive << ( zext_ln218_2_fu_530_p1 );

    SC_METHOD(thread_in_M_imag_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_in_M_real_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( zext_ln204_2_fu_412_p1 );
    sensitive << ( zext_ln218_2_fu_530_p1 );

    SC_METHOD(thread_in_M_real_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_j_1_fu_491_p2);
    sensitive << ( j2_0_reg_276 );

    SC_METHOD(thread_j_fu_397_p2);
    sensitive << ( j_0_reg_253 );

    SC_METHOD(thread_k_fu_446_p2);
    sensitive << ( k_0_reg_265 );

    SC_METHOD(thread_out_M_imag_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( zext_ln210_2_fu_466_p1 );
    sensitive << ( zext_ln223_2_fu_592_p1 );

    SC_METHOD(thread_out_M_imag_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_out_M_imag_d0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( bitcast_ln210_1_fu_480_p1 );
    sensitive << ( bitcast_ln223_1_fu_606_p1 );

    SC_METHOD(thread_out_M_imag_we0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_out_M_real_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( zext_ln210_2_fu_466_p1 );
    sensitive << ( zext_ln223_2_fu_592_p1 );

    SC_METHOD(thread_out_M_real_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_out_M_real_d0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( bitcast_ln210_fu_475_p1 );
    sensitive << ( bitcast_ln223_fu_601_p1 );

    SC_METHOD(thread_out_M_real_we0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_tmp_1_fu_379_p3);
    sensitive << ( i_0_reg_242 );

    SC_METHOD(thread_tmp_2_fu_513_p3);
    sensitive << ( i3_0_reg_287 );

    SC_METHOD(thread_tmp_3_fu_575_p3);
    sensitive << ( i4_0_reg_299 );

    SC_METHOD(thread_trunc_ln210_fu_471_p1);
    sensitive << ( buffer_out_q0 );

    SC_METHOD(thread_trunc_ln223_fu_597_p1);
    sensitive << ( buffer_out_q0 );

    SC_METHOD(thread_zext_ln199_1_fu_351_p1);
    sensitive << ( phi_ln199_1_reg_231 );

    SC_METHOD(thread_zext_ln199_fu_334_p1);
    sensitive << ( phi_ln199_reg_220 );

    SC_METHOD(thread_zext_ln203_fu_387_p1);
    sensitive << ( tmp_1_fu_379_p3 );

    SC_METHOD(thread_zext_ln204_1_fu_403_p1);
    sensitive << ( j_0_reg_253 );

    SC_METHOD(thread_zext_ln204_2_fu_412_p1);
    sensitive << ( add_ln204_fu_407_p2 );

    SC_METHOD(thread_zext_ln204_fu_418_p1);
    sensitive << ( j_0_reg_253 );

    SC_METHOD(thread_zext_ln210_1_fu_457_p1);
    sensitive << ( k_0_reg_265 );

    SC_METHOD(thread_zext_ln210_2_fu_466_p1);
    sensitive << ( add_ln210_reg_678 );

    SC_METHOD(thread_zext_ln210_fu_452_p1);
    sensitive << ( k_0_reg_265 );

    SC_METHOD(thread_zext_ln217_fu_497_p1);
    sensitive << ( j2_0_reg_276 );

    SC_METHOD(thread_zext_ln218_1_fu_521_p1);
    sensitive << ( tmp_2_fu_513_p3 );

    SC_METHOD(thread_zext_ln218_2_fu_530_p1);
    sensitive << ( add_ln218_fu_525_p2 );

    SC_METHOD(thread_zext_ln218_fu_536_p1);
    sensitive << ( i3_0_reg_287 );

    SC_METHOD(thread_zext_ln223_1_fu_583_p1);
    sensitive << ( tmp_3_fu_575_p3 );

    SC_METHOD(thread_zext_ln223_2_fu_592_p1);
    sensitive << ( add_ln223_reg_728 );

    SC_METHOD(thread_zext_ln223_fu_570_p1);
    sensitive << ( i4_0_reg_299 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln202_fu_367_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln203_fu_391_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln209_fu_440_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln216_fu_485_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln217_fu_501_p2 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( icmp_ln222_fu_558_p2 );
    sensitive << ( icmp_ln199_fu_339_p2 );
    sensitive << ( icmp_ln199_1_fu_356_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_block_state7_on_subcall_done );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_block_state13_on_subcall_done );

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000001";
    grp_fft_top_fu_310_ap_start_reg = SC_LOGIC_0;
    ap_sync_reg_grp_fft_top_fu_310_ap_ready = SC_LOGIC_0;
    ap_sync_reg_grp_fft_top_fu_310_ap_done = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fft_top_2D_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, direction, "(port)direction");
    sc_trace(mVcdFile, in_M_real_address0, "(port)in_M_real_address0");
    sc_trace(mVcdFile, in_M_real_ce0, "(port)in_M_real_ce0");
    sc_trace(mVcdFile, in_M_real_q0, "(port)in_M_real_q0");
    sc_trace(mVcdFile, in_M_imag_address0, "(port)in_M_imag_address0");
    sc_trace(mVcdFile, in_M_imag_ce0, "(port)in_M_imag_ce0");
    sc_trace(mVcdFile, in_M_imag_q0, "(port)in_M_imag_q0");
    sc_trace(mVcdFile, out_M_real_address0, "(port)out_M_real_address0");
    sc_trace(mVcdFile, out_M_real_ce0, "(port)out_M_real_ce0");
    sc_trace(mVcdFile, out_M_real_we0, "(port)out_M_real_we0");
    sc_trace(mVcdFile, out_M_real_d0, "(port)out_M_real_d0");
    sc_trace(mVcdFile, out_M_imag_address0, "(port)out_M_imag_address0");
    sc_trace(mVcdFile, out_M_imag_ce0, "(port)out_M_imag_ce0");
    sc_trace(mVcdFile, out_M_imag_we0, "(port)out_M_imag_we0");
    sc_trace(mVcdFile, out_M_imag_d0, "(port)out_M_imag_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, add_ln199_fu_328_p2, "add_ln199_fu_328_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, add_ln199_1_fu_345_p2, "add_ln199_1_fu_345_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_1_fu_373_p2, "i_1_fu_373_p2");
    sc_trace(mVcdFile, i_1_reg_641, "i_1_reg_641");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln203_fu_387_p1, "zext_ln203_fu_387_p1");
    sc_trace(mVcdFile, zext_ln203_reg_646, "zext_ln203_reg_646");
    sc_trace(mVcdFile, icmp_ln202_fu_367_p2, "icmp_ln202_fu_367_p2");
    sc_trace(mVcdFile, j_fu_397_p2, "j_fu_397_p2");
    sc_trace(mVcdFile, j_reg_655, "j_reg_655");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln203_fu_391_p2, "icmp_ln203_fu_391_p2");
    sc_trace(mVcdFile, k_fu_446_p2, "k_fu_446_p2");
    sc_trace(mVcdFile, k_reg_673, "k_reg_673");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, add_ln210_fu_461_p2, "add_ln210_fu_461_p2");
    sc_trace(mVcdFile, add_ln210_reg_678, "add_ln210_reg_678");
    sc_trace(mVcdFile, icmp_ln209_fu_440_p2, "icmp_ln209_fu_440_p2");
    sc_trace(mVcdFile, j_1_fu_491_p2, "j_1_fu_491_p2");
    sc_trace(mVcdFile, j_1_reg_691, "j_1_reg_691");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, zext_ln217_fu_497_p1, "zext_ln217_fu_497_p1");
    sc_trace(mVcdFile, zext_ln217_reg_696, "zext_ln217_reg_696");
    sc_trace(mVcdFile, icmp_ln216_fu_485_p2, "icmp_ln216_fu_485_p2");
    sc_trace(mVcdFile, i_fu_507_p2, "i_fu_507_p2");
    sc_trace(mVcdFile, i_reg_705, "i_reg_705");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, icmp_ln217_fu_501_p2, "icmp_ln217_fu_501_p2");
    sc_trace(mVcdFile, i_2_fu_564_p2, "i_2_fu_564_p2");
    sc_trace(mVcdFile, i_2_reg_723, "i_2_reg_723");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, add_ln223_fu_587_p2, "add_ln223_fu_587_p2");
    sc_trace(mVcdFile, add_ln223_reg_728, "add_ln223_reg_728");
    sc_trace(mVcdFile, icmp_ln222_fu_558_p2, "icmp_ln222_fu_558_p2");
    sc_trace(mVcdFile, buffer_out_address0, "buffer_out_address0");
    sc_trace(mVcdFile, buffer_out_ce0, "buffer_out_ce0");
    sc_trace(mVcdFile, buffer_out_we0, "buffer_out_we0");
    sc_trace(mVcdFile, buffer_out_d0, "buffer_out_d0");
    sc_trace(mVcdFile, buffer_out_q0, "buffer_out_q0");
    sc_trace(mVcdFile, buffer_in_address0, "buffer_in_address0");
    sc_trace(mVcdFile, buffer_in_ce0, "buffer_in_ce0");
    sc_trace(mVcdFile, buffer_in_we0, "buffer_in_we0");
    sc_trace(mVcdFile, buffer_in_d0, "buffer_in_d0");
    sc_trace(mVcdFile, buffer_in_q0, "buffer_in_q0");
    sc_trace(mVcdFile, grp_fft_top_fu_310_in_r_address0, "grp_fft_top_fu_310_in_r_address0");
    sc_trace(mVcdFile, grp_fft_top_fu_310_in_r_ce0, "grp_fft_top_fu_310_in_r_ce0");
    sc_trace(mVcdFile, grp_fft_top_fu_310_in_r_d0, "grp_fft_top_fu_310_in_r_d0");
    sc_trace(mVcdFile, grp_fft_top_fu_310_in_r_we0, "grp_fft_top_fu_310_in_r_we0");
    sc_trace(mVcdFile, grp_fft_top_fu_310_in_r_address1, "grp_fft_top_fu_310_in_r_address1");
    sc_trace(mVcdFile, grp_fft_top_fu_310_in_r_ce1, "grp_fft_top_fu_310_in_r_ce1");
    sc_trace(mVcdFile, grp_fft_top_fu_310_in_r_d1, "grp_fft_top_fu_310_in_r_d1");
    sc_trace(mVcdFile, grp_fft_top_fu_310_in_r_we1, "grp_fft_top_fu_310_in_r_we1");
    sc_trace(mVcdFile, grp_fft_top_fu_310_out_r_address0, "grp_fft_top_fu_310_out_r_address0");
    sc_trace(mVcdFile, grp_fft_top_fu_310_out_r_ce0, "grp_fft_top_fu_310_out_r_ce0");
    sc_trace(mVcdFile, grp_fft_top_fu_310_out_r_d0, "grp_fft_top_fu_310_out_r_d0");
    sc_trace(mVcdFile, grp_fft_top_fu_310_out_r_we0, "grp_fft_top_fu_310_out_r_we0");
    sc_trace(mVcdFile, grp_fft_top_fu_310_out_r_address1, "grp_fft_top_fu_310_out_r_address1");
    sc_trace(mVcdFile, grp_fft_top_fu_310_out_r_ce1, "grp_fft_top_fu_310_out_r_ce1");
    sc_trace(mVcdFile, grp_fft_top_fu_310_out_r_d1, "grp_fft_top_fu_310_out_r_d1");
    sc_trace(mVcdFile, grp_fft_top_fu_310_out_r_we1, "grp_fft_top_fu_310_out_r_we1");
    sc_trace(mVcdFile, grp_fft_top_fu_310_ovflo, "grp_fft_top_fu_310_ovflo");
    sc_trace(mVcdFile, grp_fft_top_fu_310_direction_ap_ack, "grp_fft_top_fu_310_direction_ap_ack");
    sc_trace(mVcdFile, grp_fft_top_fu_310_ap_start, "grp_fft_top_fu_310_ap_start");
    sc_trace(mVcdFile, grp_fft_top_fu_310_ovflo_ap_vld, "grp_fft_top_fu_310_ovflo_ap_vld");
    sc_trace(mVcdFile, grp_fft_top_fu_310_ap_done, "grp_fft_top_fu_310_ap_done");
    sc_trace(mVcdFile, grp_fft_top_fu_310_ap_ready, "grp_fft_top_fu_310_ap_ready");
    sc_trace(mVcdFile, grp_fft_top_fu_310_ap_idle, "grp_fft_top_fu_310_ap_idle");
    sc_trace(mVcdFile, grp_fft_top_fu_310_ap_continue, "grp_fft_top_fu_310_ap_continue");
    sc_trace(mVcdFile, phi_ln199_reg_220, "phi_ln199_reg_220");
    sc_trace(mVcdFile, icmp_ln199_fu_339_p2, "icmp_ln199_fu_339_p2");
    sc_trace(mVcdFile, phi_ln199_1_reg_231, "phi_ln199_1_reg_231");
    sc_trace(mVcdFile, icmp_ln199_1_fu_356_p2, "icmp_ln199_1_fu_356_p2");
    sc_trace(mVcdFile, i_0_reg_242, "i_0_reg_242");
    sc_trace(mVcdFile, j_0_reg_253, "j_0_reg_253");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, k_0_reg_265, "k_0_reg_265");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_sync_grp_fft_top_fu_310_ap_ready, "ap_sync_grp_fft_top_fu_310_ap_ready");
    sc_trace(mVcdFile, ap_sync_grp_fft_top_fu_310_ap_done, "ap_sync_grp_fft_top_fu_310_ap_done");
    sc_trace(mVcdFile, ap_block_state7_on_subcall_done, "ap_block_state7_on_subcall_done");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, j2_0_reg_276, "j2_0_reg_276");
    sc_trace(mVcdFile, i3_0_reg_287, "i3_0_reg_287");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, i4_0_reg_299, "i4_0_reg_299");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_block_state13_on_subcall_done, "ap_block_state13_on_subcall_done");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, grp_fft_top_fu_310_ap_start_reg, "grp_fft_top_fu_310_ap_start_reg");
    sc_trace(mVcdFile, ap_sync_reg_grp_fft_top_fu_310_ap_ready, "ap_sync_reg_grp_fft_top_fu_310_ap_ready");
    sc_trace(mVcdFile, ap_sync_reg_grp_fft_top_fu_310_ap_done, "ap_sync_reg_grp_fft_top_fu_310_ap_done");
    sc_trace(mVcdFile, zext_ln199_fu_334_p1, "zext_ln199_fu_334_p1");
    sc_trace(mVcdFile, zext_ln199_1_fu_351_p1, "zext_ln199_1_fu_351_p1");
    sc_trace(mVcdFile, zext_ln204_2_fu_412_p1, "zext_ln204_2_fu_412_p1");
    sc_trace(mVcdFile, zext_ln204_fu_418_p1, "zext_ln204_fu_418_p1");
    sc_trace(mVcdFile, zext_ln210_fu_452_p1, "zext_ln210_fu_452_p1");
    sc_trace(mVcdFile, zext_ln210_2_fu_466_p1, "zext_ln210_2_fu_466_p1");
    sc_trace(mVcdFile, zext_ln218_2_fu_530_p1, "zext_ln218_2_fu_530_p1");
    sc_trace(mVcdFile, zext_ln218_fu_536_p1, "zext_ln218_fu_536_p1");
    sc_trace(mVcdFile, zext_ln223_fu_570_p1, "zext_ln223_fu_570_p1");
    sc_trace(mVcdFile, zext_ln223_2_fu_592_p1, "zext_ln223_2_fu_592_p1");
    sc_trace(mVcdFile, buffer_in_M_imag_ad_fu_431_p3, "buffer_in_M_imag_ad_fu_431_p3");
    sc_trace(mVcdFile, buffer_in_M_imag_ad_1_fu_549_p3, "buffer_in_M_imag_ad_1_fu_549_p3");
    sc_trace(mVcdFile, bitcast_ln210_fu_475_p1, "bitcast_ln210_fu_475_p1");
    sc_trace(mVcdFile, bitcast_ln223_fu_601_p1, "bitcast_ln223_fu_601_p1");
    sc_trace(mVcdFile, bitcast_ln210_1_fu_480_p1, "bitcast_ln210_1_fu_480_p1");
    sc_trace(mVcdFile, bitcast_ln223_1_fu_606_p1, "bitcast_ln223_1_fu_606_p1");
    sc_trace(mVcdFile, tmp_1_fu_379_p3, "tmp_1_fu_379_p3");
    sc_trace(mVcdFile, zext_ln204_1_fu_403_p1, "zext_ln204_1_fu_403_p1");
    sc_trace(mVcdFile, add_ln204_fu_407_p2, "add_ln204_fu_407_p2");
    sc_trace(mVcdFile, bitcast_ln204_1_fu_427_p1, "bitcast_ln204_1_fu_427_p1");
    sc_trace(mVcdFile, bitcast_ln204_fu_423_p1, "bitcast_ln204_fu_423_p1");
    sc_trace(mVcdFile, zext_ln210_1_fu_457_p1, "zext_ln210_1_fu_457_p1");
    sc_trace(mVcdFile, trunc_ln210_fu_471_p1, "trunc_ln210_fu_471_p1");
    sc_trace(mVcdFile, grp_fu_318_p4, "grp_fu_318_p4");
    sc_trace(mVcdFile, tmp_2_fu_513_p3, "tmp_2_fu_513_p3");
    sc_trace(mVcdFile, zext_ln218_1_fu_521_p1, "zext_ln218_1_fu_521_p1");
    sc_trace(mVcdFile, add_ln218_fu_525_p2, "add_ln218_fu_525_p2");
    sc_trace(mVcdFile, bitcast_ln218_1_fu_545_p1, "bitcast_ln218_1_fu_545_p1");
    sc_trace(mVcdFile, bitcast_ln218_fu_541_p1, "bitcast_ln218_fu_541_p1");
    sc_trace(mVcdFile, tmp_3_fu_575_p3, "tmp_3_fu_575_p3");
    sc_trace(mVcdFile, zext_ln223_1_fu_583_p1, "zext_ln223_1_fu_583_p1");
    sc_trace(mVcdFile, trunc_ln223_fu_597_p1, "trunc_ln223_fu_597_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

fft_top_2D::~fft_top_2D() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete buffer_out_U;
    delete buffer_in_U;
    delete grp_fft_top_fu_310;
}

void fft_top_2D::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_logic_1;
}

void fft_top_2D::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv64_0;
}

void fft_top_2D::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_sync_reg_grp_fft_top_fu_310_ap_done = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
              esl_seteq<1,1,1>(ap_block_state7_on_subcall_done.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
              esl_seteq<1,1,1>(ap_block_state13_on_subcall_done.read(), ap_const_boolean_0)))) {
            ap_sync_reg_grp_fft_top_fu_310_ap_done = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_fft_top_fu_310_ap_done.read())) {
            ap_sync_reg_grp_fft_top_fu_310_ap_done = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_sync_reg_grp_fft_top_fu_310_ap_ready = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
              esl_seteq<1,1,1>(ap_block_state7_on_subcall_done.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
              esl_seteq<1,1,1>(ap_block_state13_on_subcall_done.read(), ap_const_boolean_0)))) {
            ap_sync_reg_grp_fft_top_fu_310_ap_ready = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_fft_top_fu_310_ap_ready.read())) {
            ap_sync_reg_grp_fft_top_fu_310_ap_ready = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_fft_top_fu_310_ap_start_reg = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
              esl_seteq<1,1,1>(icmp_ln203_fu_391_p2.read(), ap_const_lv1_1)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_grp_fft_top_fu_310_ap_ready.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
              esl_seteq<1,1,1>(icmp_ln217_fu_501_p2.read(), ap_const_lv1_1)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_grp_fft_top_fu_310_ap_ready.read())))) {
            grp_fft_top_fu_310_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_fft_top_fu_310_ap_ready.read())) {
            grp_fft_top_fu_310_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        i3_0_reg_287 = i_reg_705.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln216_fu_485_p2.read()))) {
        i3_0_reg_287 = ap_const_lv8_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        i4_0_reg_299 = i_2_reg_723.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
                esl_seteq<1,1,1>(ap_block_state13_on_subcall_done.read(), ap_const_boolean_0))) {
        i4_0_reg_299 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln209_fu_440_p2.read(), ap_const_lv1_1))) {
        i_0_reg_242 = i_1_reg_641.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(icmp_ln199_1_fu_356_p2.read(), ap_const_lv1_1))) {
        i_0_reg_242 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln202_fu_367_p2.read(), ap_const_lv1_1))) {
        j2_0_reg_276 = ap_const_lv8_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
                esl_seteq<1,1,1>(icmp_ln222_fu_558_p2.read(), ap_const_lv1_1))) {
        j2_0_reg_276 = j_1_reg_691.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_0_reg_253 = j_reg_655.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln202_fu_367_p2.read(), ap_const_lv1_0))) {
        j_0_reg_253 = ap_const_lv8_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        k_0_reg_265 = k_reg_673.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_block_state7_on_subcall_done.read(), ap_const_boolean_0))) {
        k_0_reg_265 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln199_fu_339_p2.read(), ap_const_lv1_1))) {
        phi_ln199_1_reg_231 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_1_fu_356_p2.read()))) {
        phi_ln199_1_reg_231 = add_ln199_1_fu_345_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln199_fu_339_p2.read()))) {
        phi_ln199_reg_220 = add_ln199_fu_328_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        phi_ln199_reg_220 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln209_fu_440_p2.read()))) {
        add_ln210_reg_678 = add_ln210_fu_461_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln222_fu_558_p2.read()))) {
        add_ln223_reg_728 = add_ln223_fu_587_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_1_reg_641 = i_1_fu_373_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        i_2_reg_723 = i_2_fu_564_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        i_reg_705 = i_fu_507_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        j_1_reg_691 = j_1_fu_491_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        j_reg_655 = j_fu_397_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        k_reg_673 = k_fu_446_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln202_fu_367_p2.read(), ap_const_lv1_0))) {
        zext_ln203_reg_646 = zext_ln203_fu_387_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln216_fu_485_p2.read()))) {
        zext_ln217_reg_696 = zext_ln217_fu_497_p1.read();
    }
}

void fft_top_2D::thread_add_ln199_1_fu_345_p2() {
    add_ln199_1_fu_345_p2 = (!phi_ln199_1_reg_231.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(phi_ln199_1_reg_231.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void fft_top_2D::thread_add_ln199_fu_328_p2() {
    add_ln199_fu_328_p2 = (!phi_ln199_reg_220.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(phi_ln199_reg_220.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void fft_top_2D::thread_add_ln204_fu_407_p2() {
    add_ln204_fu_407_p2 = (!zext_ln203_reg_646.read().is_01() || !zext_ln204_1_fu_403_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln203_reg_646.read()) + sc_biguint<16>(zext_ln204_1_fu_403_p1.read()));
}

void fft_top_2D::thread_add_ln210_fu_461_p2() {
    add_ln210_fu_461_p2 = (!zext_ln210_1_fu_457_p1.read().is_01() || !zext_ln203_reg_646.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln210_1_fu_457_p1.read()) + sc_biguint<16>(zext_ln203_reg_646.read()));
}

void fft_top_2D::thread_add_ln218_fu_525_p2() {
    add_ln218_fu_525_p2 = (!zext_ln217_reg_696.read().is_01() || !zext_ln218_1_fu_521_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln217_reg_696.read()) + sc_biguint<16>(zext_ln218_1_fu_521_p1.read()));
}

void fft_top_2D::thread_add_ln223_fu_587_p2() {
    add_ln223_fu_587_p2 = (!zext_ln223_1_fu_583_p1.read().is_01() || !zext_ln217_reg_696.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln223_1_fu_583_p1.read()) + sc_biguint<16>(zext_ln217_reg_696.read()));
}

void fft_top_2D::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void fft_top_2D::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void fft_top_2D::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void fft_top_2D::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void fft_top_2D::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void fft_top_2D::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void fft_top_2D::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void fft_top_2D::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void fft_top_2D::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void fft_top_2D::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void fft_top_2D::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void fft_top_2D::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void fft_top_2D::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void fft_top_2D::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void fft_top_2D::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void fft_top_2D::thread_ap_block_state13_on_subcall_done() {
    ap_block_state13_on_subcall_done = esl_seteq<1,1,1>(ap_const_logic_0, (ap_sync_grp_fft_top_fu_310_ap_ready.read() & ap_sync_grp_fft_top_fu_310_ap_done.read()));
}

void fft_top_2D::thread_ap_block_state7_on_subcall_done() {
    ap_block_state7_on_subcall_done = esl_seteq<1,1,1>(ap_const_logic_0, (ap_sync_grp_fft_top_fu_310_ap_ready.read() & ap_sync_grp_fft_top_fu_310_ap_done.read()));
}

void fft_top_2D::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(icmp_ln216_fu_485_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void fft_top_2D::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void fft_top_2D::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(icmp_ln216_fu_485_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void fft_top_2D::thread_ap_sync_grp_fft_top_fu_310_ap_done() {
    ap_sync_grp_fft_top_fu_310_ap_done = (grp_fft_top_fu_310_ap_done.read() | ap_sync_reg_grp_fft_top_fu_310_ap_done.read());
}

void fft_top_2D::thread_ap_sync_grp_fft_top_fu_310_ap_ready() {
    ap_sync_grp_fft_top_fu_310_ap_ready = (grp_fft_top_fu_310_ap_ready.read() | ap_sync_reg_grp_fft_top_fu_310_ap_ready.read());
}

void fft_top_2D::thread_bitcast_ln204_1_fu_427_p1() {
    bitcast_ln204_1_fu_427_p1 = in_M_imag_q0.read();
}

void fft_top_2D::thread_bitcast_ln204_fu_423_p1() {
    bitcast_ln204_fu_423_p1 = in_M_real_q0.read();
}

void fft_top_2D::thread_bitcast_ln210_1_fu_480_p1() {
    bitcast_ln210_1_fu_480_p1 = grp_fu_318_p4.read();
}

void fft_top_2D::thread_bitcast_ln210_fu_475_p1() {
    bitcast_ln210_fu_475_p1 = trunc_ln210_fu_471_p1.read();
}

void fft_top_2D::thread_bitcast_ln218_1_fu_545_p1() {
    bitcast_ln218_1_fu_545_p1 = in_M_imag_q0.read();
}

void fft_top_2D::thread_bitcast_ln218_fu_541_p1() {
    bitcast_ln218_fu_541_p1 = in_M_real_q0.read();
}

void fft_top_2D::thread_bitcast_ln223_1_fu_606_p1() {
    bitcast_ln223_1_fu_606_p1 = grp_fu_318_p4.read();
}

void fft_top_2D::thread_bitcast_ln223_fu_601_p1() {
    bitcast_ln223_fu_601_p1 = trunc_ln223_fu_597_p1.read();
}

void fft_top_2D::thread_buffer_in_M_imag_ad_1_fu_549_p3() {
    buffer_in_M_imag_ad_1_fu_549_p3 = esl_concat<32,32>(bitcast_ln218_1_fu_545_p1.read(), bitcast_ln218_fu_541_p1.read());
}

void fft_top_2D::thread_buffer_in_M_imag_ad_fu_431_p3() {
    buffer_in_M_imag_ad_fu_431_p3 = esl_concat<32,32>(bitcast_ln204_1_fu_427_p1.read(), bitcast_ln204_fu_423_p1.read());
}

void fft_top_2D::thread_buffer_in_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        buffer_in_address0 =  (sc_lv<7>) (zext_ln218_fu_536_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        buffer_in_address0 =  (sc_lv<7>) (zext_ln204_fu_418_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        buffer_in_address0 =  (sc_lv<7>) (zext_ln199_fu_334_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        buffer_in_address0 = grp_fft_top_fu_310_in_r_address0.read();
    } else {
        buffer_in_address0 = "XXXXXXX";
    }
}

void fft_top_2D::thread_buffer_in_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        buffer_in_ce0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        buffer_in_ce0 = grp_fft_top_fu_310_in_r_ce0.read();
    } else {
        buffer_in_ce0 = ap_const_logic_0;
    }
}

void fft_top_2D::thread_buffer_in_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        buffer_in_d0 = buffer_in_M_imag_ad_1_fu_549_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        buffer_in_d0 = buffer_in_M_imag_ad_fu_431_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        buffer_in_d0 = ap_const_lv64_0;
    } else {
        buffer_in_d0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fft_top_2D::thread_buffer_in_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        buffer_in_we0 = ap_const_logic_1;
    } else {
        buffer_in_we0 = ap_const_logic_0;
    }
}

void fft_top_2D::thread_buffer_out_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        buffer_out_address0 =  (sc_lv<7>) (zext_ln223_fu_570_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        buffer_out_address0 =  (sc_lv<7>) (zext_ln210_fu_452_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        buffer_out_address0 =  (sc_lv<7>) (zext_ln199_1_fu_351_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        buffer_out_address0 = grp_fft_top_fu_310_out_r_address0.read();
    } else {
        buffer_out_address0 = "XXXXXXX";
    }
}

void fft_top_2D::thread_buffer_out_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        buffer_out_ce0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        buffer_out_ce0 = grp_fft_top_fu_310_out_r_ce0.read();
    } else {
        buffer_out_ce0 = ap_const_logic_0;
    }
}

void fft_top_2D::thread_buffer_out_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        buffer_out_d0 = ap_const_lv64_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        buffer_out_d0 = grp_fft_top_fu_310_out_r_d0.read();
    } else {
        buffer_out_d0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fft_top_2D::thread_buffer_out_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        buffer_out_we0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        buffer_out_we0 = grp_fft_top_fu_310_out_r_we0.read();
    } else {
        buffer_out_we0 = ap_const_logic_0;
    }
}

void fft_top_2D::thread_grp_fft_top_fu_310_ap_continue() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_block_state7_on_subcall_done.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
          esl_seteq<1,1,1>(ap_block_state13_on_subcall_done.read(), ap_const_boolean_0)))) {
        grp_fft_top_fu_310_ap_continue = ap_const_logic_1;
    } else {
        grp_fft_top_fu_310_ap_continue = ap_const_logic_0;
    }
}

void fft_top_2D::thread_grp_fft_top_fu_310_ap_start() {
    grp_fft_top_fu_310_ap_start = grp_fft_top_fu_310_ap_start_reg.read();
}

void fft_top_2D::thread_grp_fu_318_p4() {
    grp_fu_318_p4 = buffer_out_q0.read().range(63, 32);
}

void fft_top_2D::thread_i_1_fu_373_p2() {
    i_1_fu_373_p2 = (!i_0_reg_242.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(i_0_reg_242.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void fft_top_2D::thread_i_2_fu_564_p2() {
    i_2_fu_564_p2 = (!i4_0_reg_299.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(i4_0_reg_299.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void fft_top_2D::thread_i_fu_507_p2() {
    i_fu_507_p2 = (!i3_0_reg_287.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(i3_0_reg_287.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void fft_top_2D::thread_icmp_ln199_1_fu_356_p2() {
    icmp_ln199_1_fu_356_p2 = (!phi_ln199_1_reg_231.read().is_01() || !ap_const_lv7_7F.is_01())? sc_lv<1>(): sc_lv<1>(phi_ln199_1_reg_231.read() == ap_const_lv7_7F);
}

void fft_top_2D::thread_icmp_ln199_fu_339_p2() {
    icmp_ln199_fu_339_p2 = (!phi_ln199_reg_220.read().is_01() || !ap_const_lv7_7F.is_01())? sc_lv<1>(): sc_lv<1>(phi_ln199_reg_220.read() == ap_const_lv7_7F);
}

void fft_top_2D::thread_icmp_ln202_fu_367_p2() {
    icmp_ln202_fu_367_p2 = (!i_0_reg_242.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_242.read() == ap_const_lv8_80);
}

void fft_top_2D::thread_icmp_ln203_fu_391_p2() {
    icmp_ln203_fu_391_p2 = (!j_0_reg_253.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_253.read() == ap_const_lv8_80);
}

void fft_top_2D::thread_icmp_ln209_fu_440_p2() {
    icmp_ln209_fu_440_p2 = (!k_0_reg_265.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(k_0_reg_265.read() == ap_const_lv8_80);
}

void fft_top_2D::thread_icmp_ln216_fu_485_p2() {
    icmp_ln216_fu_485_p2 = (!j2_0_reg_276.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(j2_0_reg_276.read() == ap_const_lv8_80);
}

void fft_top_2D::thread_icmp_ln217_fu_501_p2() {
    icmp_ln217_fu_501_p2 = (!i3_0_reg_287.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(i3_0_reg_287.read() == ap_const_lv8_80);
}

void fft_top_2D::thread_icmp_ln222_fu_558_p2() {
    icmp_ln222_fu_558_p2 = (!i4_0_reg_299.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(i4_0_reg_299.read() == ap_const_lv8_80);
}

void fft_top_2D::thread_in_M_imag_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        in_M_imag_address0 =  (sc_lv<14>) (zext_ln218_2_fu_530_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        in_M_imag_address0 =  (sc_lv<14>) (zext_ln204_2_fu_412_p1.read());
    } else {
        in_M_imag_address0 =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
    }
}

void fft_top_2D::thread_in_M_imag_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        in_M_imag_ce0 = ap_const_logic_1;
    } else {
        in_M_imag_ce0 = ap_const_logic_0;
    }
}

void fft_top_2D::thread_in_M_real_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        in_M_real_address0 =  (sc_lv<14>) (zext_ln218_2_fu_530_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        in_M_real_address0 =  (sc_lv<14>) (zext_ln204_2_fu_412_p1.read());
    } else {
        in_M_real_address0 =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
    }
}

void fft_top_2D::thread_in_M_real_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        in_M_real_ce0 = ap_const_logic_1;
    } else {
        in_M_real_ce0 = ap_const_logic_0;
    }
}

void fft_top_2D::thread_j_1_fu_491_p2() {
    j_1_fu_491_p2 = (!j2_0_reg_276.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(j2_0_reg_276.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void fft_top_2D::thread_j_fu_397_p2() {
    j_fu_397_p2 = (!j_0_reg_253.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(j_0_reg_253.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void fft_top_2D::thread_k_fu_446_p2() {
    k_fu_446_p2 = (!k_0_reg_265.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(k_0_reg_265.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void fft_top_2D::thread_out_M_imag_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        out_M_imag_address0 =  (sc_lv<14>) (zext_ln223_2_fu_592_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        out_M_imag_address0 =  (sc_lv<14>) (zext_ln210_2_fu_466_p1.read());
    } else {
        out_M_imag_address0 =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
    }
}

void fft_top_2D::thread_out_M_imag_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        out_M_imag_ce0 = ap_const_logic_1;
    } else {
        out_M_imag_ce0 = ap_const_logic_0;
    }
}

void fft_top_2D::thread_out_M_imag_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        out_M_imag_d0 = bitcast_ln223_1_fu_606_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        out_M_imag_d0 = bitcast_ln210_1_fu_480_p1.read();
    } else {
        out_M_imag_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fft_top_2D::thread_out_M_imag_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        out_M_imag_we0 = ap_const_logic_1;
    } else {
        out_M_imag_we0 = ap_const_logic_0;
    }
}

void fft_top_2D::thread_out_M_real_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        out_M_real_address0 =  (sc_lv<14>) (zext_ln223_2_fu_592_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        out_M_real_address0 =  (sc_lv<14>) (zext_ln210_2_fu_466_p1.read());
    } else {
        out_M_real_address0 =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
    }
}

void fft_top_2D::thread_out_M_real_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        out_M_real_ce0 = ap_const_logic_1;
    } else {
        out_M_real_ce0 = ap_const_logic_0;
    }
}

void fft_top_2D::thread_out_M_real_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        out_M_real_d0 = bitcast_ln223_fu_601_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        out_M_real_d0 = bitcast_ln210_fu_475_p1.read();
    } else {
        out_M_real_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fft_top_2D::thread_out_M_real_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        out_M_real_we0 = ap_const_logic_1;
    } else {
        out_M_real_we0 = ap_const_logic_0;
    }
}

void fft_top_2D::thread_tmp_1_fu_379_p3() {
    tmp_1_fu_379_p3 = esl_concat<8,7>(i_0_reg_242.read(), ap_const_lv7_0);
}

void fft_top_2D::thread_tmp_2_fu_513_p3() {
    tmp_2_fu_513_p3 = esl_concat<8,7>(i3_0_reg_287.read(), ap_const_lv7_0);
}

void fft_top_2D::thread_tmp_3_fu_575_p3() {
    tmp_3_fu_575_p3 = esl_concat<8,7>(i4_0_reg_299.read(), ap_const_lv7_0);
}

void fft_top_2D::thread_trunc_ln210_fu_471_p1() {
    trunc_ln210_fu_471_p1 = buffer_out_q0.read().range(32-1, 0);
}

void fft_top_2D::thread_trunc_ln223_fu_597_p1() {
    trunc_ln223_fu_597_p1 = buffer_out_q0.read().range(32-1, 0);
}

void fft_top_2D::thread_zext_ln199_1_fu_351_p1() {
    zext_ln199_1_fu_351_p1 = esl_zext<64,7>(phi_ln199_1_reg_231.read());
}

void fft_top_2D::thread_zext_ln199_fu_334_p1() {
    zext_ln199_fu_334_p1 = esl_zext<64,7>(phi_ln199_reg_220.read());
}

void fft_top_2D::thread_zext_ln203_fu_387_p1() {
    zext_ln203_fu_387_p1 = esl_zext<16,15>(tmp_1_fu_379_p3.read());
}

void fft_top_2D::thread_zext_ln204_1_fu_403_p1() {
    zext_ln204_1_fu_403_p1 = esl_zext<16,8>(j_0_reg_253.read());
}

void fft_top_2D::thread_zext_ln204_2_fu_412_p1() {
    zext_ln204_2_fu_412_p1 = esl_zext<64,16>(add_ln204_fu_407_p2.read());
}

void fft_top_2D::thread_zext_ln204_fu_418_p1() {
    zext_ln204_fu_418_p1 = esl_zext<64,8>(j_0_reg_253.read());
}

void fft_top_2D::thread_zext_ln210_1_fu_457_p1() {
    zext_ln210_1_fu_457_p1 = esl_zext<16,8>(k_0_reg_265.read());
}

void fft_top_2D::thread_zext_ln210_2_fu_466_p1() {
    zext_ln210_2_fu_466_p1 = esl_zext<64,16>(add_ln210_reg_678.read());
}

void fft_top_2D::thread_zext_ln210_fu_452_p1() {
    zext_ln210_fu_452_p1 = esl_zext<64,8>(k_0_reg_265.read());
}

void fft_top_2D::thread_zext_ln217_fu_497_p1() {
    zext_ln217_fu_497_p1 = esl_zext<16,8>(j2_0_reg_276.read());
}

void fft_top_2D::thread_zext_ln218_1_fu_521_p1() {
    zext_ln218_1_fu_521_p1 = esl_zext<16,15>(tmp_2_fu_513_p3.read());
}

void fft_top_2D::thread_zext_ln218_2_fu_530_p1() {
    zext_ln218_2_fu_530_p1 = esl_zext<64,16>(add_ln218_fu_525_p2.read());
}

void fft_top_2D::thread_zext_ln218_fu_536_p1() {
    zext_ln218_fu_536_p1 = esl_zext<64,8>(i3_0_reg_287.read());
}

void fft_top_2D::thread_zext_ln223_1_fu_583_p1() {
    zext_ln223_1_fu_583_p1 = esl_zext<16,15>(tmp_3_fu_575_p3.read());
}

void fft_top_2D::thread_zext_ln223_2_fu_592_p1() {
    zext_ln223_2_fu_592_p1 = esl_zext<64,16>(add_ln223_reg_728.read());
}

void fft_top_2D::thread_zext_ln223_fu_570_p1() {
    zext_ln223_fu_570_p1 = esl_zext<64,8>(i4_0_reg_299.read());
}

void fft_top_2D::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln199_fu_339_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln199_1_fu_356_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln202_fu_367_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln203_fu_391_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_block_state7_on_subcall_done.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln209_fu_440_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(icmp_ln216_fu_485_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(icmp_ln217_fu_501_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(ap_block_state13_on_subcall_done.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 8192 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(icmp_ln222_fu_558_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state15;
            }
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<15>) ("XXXXXXXXXXXXXXX");
            break;
    }
}

}

